### ISSUE TITLE
Carpeted trapdoor texture rotated

### ISSUE THREAD

**Issue by MrVirtualis** [KnightMiner/Inspirations#100]
While doing a texturepack for your mod, I noticed something strange:
The texture for the carpeted trapdoor flips when opening/closing it.
Meaning, e.g. when the door is closed the pattern is vertical, when closed horizontal (or vise versa, can't remember right now).
Or in other words: let's say, when closed the planks in the texture go from left to right. When opening the door, they go from top to bottom, although they should still go from left to right.
When using regular flat textures this is not that obvious, but with parallax it kind of jumps in your face :D

**Comment by TeamSpen210** [comment]
You'll want to check the JSON block models, and change the UVs.

**Comment by KnightMiner** [comment]
Yeah, this is a side effect of me using UV Lock to prevent the wool texture from rotating and not matching normal carpet. Its not trivial to fix without going into additional models, so I cannot see myself changing anything.

It is possible to adjust the models using the blockstate file, might not be the cleanest thing but possible.
