### ISSUE TITLE
Zen: Foundry cauldron support?

### ISSUE THREAD

**Issue by ManMan36** [KnightMiner/Inspirations#102]
The Zen Foundry mod adds a bronze cauldron. I was wondering if it would be possible to support the cauldron recipes on Zen's bronze cauldron.

**Comment by KnightMiner** [comment]
I have no plans to add support for custom cauldrons on my side, it requires a block substitution which is bad taste to do to other mod's blocks. They can easily add support on their side like the mod [More Cauldrons](https://minecraft.curseforge.com/projects/more-cauldrons) does.
