### ISSUE TITLE
Cauldron not recognized by Salis Mundus to create Thaumcraft Crucible

### ISSUE THREAD

**Issue by Dragnier** [KnightMiner/Inspirations#103]
Tried to right click on the cauldron with salis mundus and nothing happens. I know there is an option to disable the cauldron functionality, but that defeats the purpose of having both mods installed.

**Comment by Dragnier** [comment]
Never mind... I thought I had already gotten the research for it unlocked, but apparently clicking complete didn't take and I had to go back and re-do it. It works now and wasn't anything to do with Inspirations.

**Comment by eggyplantsu** [comment]
Note for anyone still playing on 1.12
If one still has issues stuck on the salis mundus cauldron conversion part of the thaumonomicons alchemy research.
go to configs,  find  S:extendCauldron=
and set it to "simple".
