### ISSUE TITLE
[Suggestion] Quark Tomes should be worth more for enchanting power

### ISSUE THREAD

**Issue by Insane-96** [KnightMiner/Inspirations#104]
Right now a Bookshelf full of normal books is worth 1.5 enchanting power, a bookshelf full of enchanted books is worth 2.5 enchanting power, quark tomes should be worth more since are pretty rare, like 3.5 / 4.0?

**Comment by KnightMiner** [comment]
I don't think I will hardcode in specific support for other mods for that feature. Instead, I think the best approach is a config for enchanting power of books. That will also allow modded magical books to be more powerful, papers to be weaker, or someone to disable the boosted enchanting power entirely

**Comment by KnightMiner** [comment]
Fixed in 0.2.4
