### ISSUE TITLE
Dispensers always get water from filled cauldrons containing any liquid

### ISSUE THREAD

**Issue by fer22f** [KnightMiner/Inspirations#106]
I believe this is a case of vanilla Minecraft behavior with the empty bucket acting on cauldrons like if they were vanilla cauldrons.

**Comment by KnightMiner** [comment]
Please post a copy of your config, I need to know if you disabled any features which might affect this, as in my testing any fluid worked fine

**Comment by fer22f** [comment]
Yep, nevermind, the issue is totally on my end. It was a conflict with RedstonePlusPlus which adds these interactions (filling of water bottles and buckets), disabling those in the configs did the trick.
