### ISSUE TITLE
[suggestion] cauldrons having the heat from their fluid content

### ISSUE THREAD

**Issue by majijn** [KnightMiner/Inspirations#110]
im not sure how much of a longshot it is, but how feasible would it be for , for example, cauldrons containing astral sorcery liquid starlight or vanilla lava  to have the respective fluid's heat?

Idea came to me while messing around with IE's thermoelectric generators in a test world.

**Comment by KnightMiner** [comment]
What do you mean by heat? IE's generator uses its own registry to handle that, so not much I can do for that one case.

**Comment by majijn** [comment]
dont fluids have their heat heat registered somewhere? 

looked some examples up
https://github.com/CoFH/ThermalFoundation/blob/1.12/src/main/java/cofh/thermalfoundation/init/TFFluids.java
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/block/fluid/FluidLiquidStarlight.java

**Comment by KnightMiner** [comment]
Fluids have a temperature, but the cauldron is not a fluid. IE I assume detects there is a fluid then fetches it's temp, no practical way for me to get it to detect that the cauldron is a fluid container. I return a fluid tank capability from it, which is as much as I can do.

**Comment by majijn** [comment]
fair enough!
