### ISSUE TITLE
BlockBlockCrop doesn't support replacement

### ISSUE THREAD

**Issue by Shadows-of-Fire** [KnightMiner/Inspirations#112]
Holding `Block` objects is bad, `IRegstryDelegate<Block>` good.
Line in question: https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/tweaks/block/BlockBlockCrop.java#L16

**Comment by KnightMiner** [comment]
Fixed in 0.2.4
