### ISSUE TITLE
IE pipes, IE barrels, fluid funnels, fluid funnel's taps, ceramic's faucet and channels, cant interact with the cauldron properly, 

### ISSUE THREAD

**Issue by majijn** [KnightMiner/Inspirations#113]
forge: 14.23.5.2814
ceramics: 1.3.6
immersive engineering : 0.12.89
inspirations : 0.2.3
fluid funnel : 1.3.0

im not sure if it's something ive done or simply not included but for the last couple of weeks less and less mods have been able to interact with the cauldron
I have it set enabled for potions, and bigger inventory, 

but only the immersive engineering pump can input and output properly on the cauldron in my pack

**Comment by KnightMiner** [comment]
Yes, this is an issue described in the cauldron fluid handler logic, you must fill in 250mb increments. Ceramics does 10mb. If you need to, use a dispenser to fill them.
