### ISSUE TITLE
Can't access bookshelf GUI when holding an item in the offhand

### ISSUE THREAD

**Issue by genandnic** [KnightMiner/Inspirations#116]

**Comment by KnightMiner** [comment]
This sounds intentional, as I recall its not supposed to let you open the GUI when clicking any book slot unless you are sneaking.

If you want to open the GUI regardless of holding an item or sneaking, just click the wood instead of a book slot.

**Comment by KnightMiner** [comment]
Closing for lack of response. From testing in game, all interactions felt as expected, as the bookshelf normally does not open the UI if you have anything in your hand when sneaking, vanilla passes the logic to the item.
