### ISSUE TITLE
[Question/feature request] Better cauldrons recipe system

### ISSUE THREAD

**Issue by Invincible92** [KnightMiner/Inspirations#117]
Hi there KnightMiner

I've opened this issue in order to know if the Better Cauldrons sub-module recipe system of the mods supports adding a custom recipe with more than one possible output. Reading the Crafttweaker wiki seems to be outputting only one possible item (correct me if I am wrong). 

If it only supports one output, could the recipe system be expanded to allow multiple outputs of an input item?

Thanks for your kind attention.

**Comment by KnightMiner** [comment]
I have no plans for multiple outputs, that strays a bit too far from the vanilla cauldron and makes the API a lot messier. The only exception is containers, so if you use something like a water bucket on the cauldron you get back the bucket.
