### ISSUE TITLE
[Suggestion] Ability to change bookshelf position on block

### ISSUE THREAD

**Issue by LordErroi** [KnightMiner/Inspirations#118]
It would be a pleasant addition to be able to adjust which section of the block bookshelves occupy, so that they can either be sunken into a wall or placed flush with surrounding blocks, similarly to Bibliocraft's bookcases.

![2019-04-12_10 34 29](https://user-images.githubusercontent.com/28904835/56058820-5c8ebc80-5d17-11e9-93b7-67d49c7fbbca.png)
![2019-04-12_10 34 31](https://user-images.githubusercontent.com/28904835/56058830-631d3400-5d17-11e9-9d0c-2202f7ceaf0d.png)
![2019-04-12_10 34 32](https://user-images.githubusercontent.com/28904835/56058841-6d3f3280-5d17-11e9-9fce-d8a258ef4343.png)

I actually didn't even know about the middle option until I was taking the screenshots for this suggestion, but I included it anyway for completeness' sake.

**Comment by KnightMiner** [comment]
I like this idea, but because of how I have the metadata set up it would not be the cleanest to implement without breaking old worlds. I think I will definitely add it once I port to 1.14, not sure if I will add it for 1.12

**Comment by KnightMiner** [comment]
I have on my notes for 1.14 to added bookshelves in the front of the block. I do not plan to add middle bookshelves at this time, but I would like to have "double bookshelves" where the shelf is in the front and back of the block
