### ISSUE TITLE
[Request] Stair carpet compatibility with Quark's leaf carpet

### ISSUE THREAD

**Issue by MorzanTLD** [KnightMiner/Inspirations#119]
It would be nice if leaf carpets from Quark worked like normal carpets on stairs as it could be used as a nice abandoned look for builds.

Note: This also doesn't work for Chisel's carpets

**Comment by KnightMiner** [comment]
I have no current plans to implement compatibility with other mod's blocks, as it requires a block substitution which is very bad practice on other mod's blocks. Vazkii has mentioned the idea of implementing carpet stairs over in Quark, so if you want that feature your best bet is asking in Quark.
