### ISSUE TITLE
Security of key and lock

### ISSUE THREAD

**Issue by Snownee** [KnightMiner/Inspirations#12]
* Hopper can access to a locked container
* Locked container can be simply broken

**Comment by KnightMiner** [comment]
All I do is expose the vanilla logic. If vanilla allows these that is on them.

**Comment by Snownee** [comment]
So what the use of a lock if there is another way to access a container?

**Comment by KnightMiner** [comment]
It's a deterent, not perfect security. Like real life locks. The idea is you will know if someone is stealing from you because they broke your chest.

Nothing I can do about hoppers, that's really a vanilla bug that it allows that.

**Comment by Snownee** [comment]
OK I see
