### ISSUE TITLE
Cannot place Biomes O' Plenty flowers on mulch blocks

### ISSUE THREAD

**Issue by slowbr0** [KnightMiner/Inspirations#121]
Not sure if this is a compatibility issue as the mulch accepts flowers from other mods and the BoP flowers can be placed onto such things as modded flower pots.

**Comment by KnightMiner** [comment]
Biomes O Plenty bug, they need to return `EnumPlantType.Plains` from `getPlantType` for their block.

**Comment by slowbr0** [comment]
Thanks for the replay. I opened an issue with Biomes O' Plenty.

**Comment by KnightMiner** [comment]
Looks like Biomes O' Plenty closed the issue on their tracker. As there is nothing I can do without hacks on my side, I will just have to call their plants unsupported.
