### ISSUE TITLE
Cauldron causes duping, voiding, and crashes

### ISSUE THREAD

**Issue by josephcsible** [KnightMiner/Inspirations#124]
Cauldrons can't contain arbitrarily small amounts of fluids like most containers can. This is why Forge didn't include an IFluidHandler for it. The one that Inspirations provides causes all sorts of bad bugs with different mods. Here's what I've seen so far:

# XNet
* Prepare a container that has less than 1000mB of free space for a fluid
* Set XNet to extract that fluid from a cauldron and insert it into said container
* Result: The game will crash, because CauldronTank#drain returns non-null for a 1000-sized FluidStack, but null for smaller ones

# Mekanism
* Put some fluid in a cauldron
* Attach a mechanical pipe to the cauldron, and set it to extract from it
* "Prime" the pipe by adding fluid to the cauldron until the pipe is full and the cauldron stops draining
* Connect the other end of the pipe to something that uses less than 1000mB of that fluid at a time
* Result: The pipe will endlessly supply fluid without ever running out or consuming any more from the cauldron

**Comment by KnightMiner** [comment]
This is on those other mods, they are perfectly capable of not crashing when my fluid handler returns null, and if you don't want to deal with it, disable the cauldron fluid handler in the config. Feel free to forward this to the affected mods, but there is nothing I can do on my side.
