### ISSUE TITLE
Atum's netherwart alternative not being caught as a valid input for cauldron potion making

### ISSUE THREAD

**Issue by majijn** [KnightMiner/Inspirations#127]
girafi gave me this link for the recipe wrapper in case you needed it.

https://github.com/TeamMetallurgy/Atum2/blob/master/src/main/java/com/teammetallurgy/atum/utils/recipe/BrewingRecipeOreDictNBT.java

**Comment by KnightMiner** [comment]
Fixed in 0.2.5
