### ISSUE TITLE
Dyes in JEI not rendering

### ISSUE THREAD

**Issue by IronPiston** [KnightMiner/Inspirations#129]
The recipes involving using a dye on a cauldron full of water do not appear to render in JEI. The dyes do render when they are used to dye something to a different color.
![2019-06-13_13 46 08](https://user-images.githubusercontent.com/11603684/59459145-b37d4480-8de1-11e9-8fb7-5c8ef5c01ffe.png)
![2019-06-13_13 46 24](https://user-images.githubusercontent.com/11603684/59459150-b6783500-8de1-11e9-9ab0-35f6329e8083.png)
![2019-06-13_13 46 26](https://user-images.githubusercontent.com/11603684/59459154-b841f880-8de1-11e9-8f7c-1ef5770f06b0.png)

Tested using the latest version of JEI(4.15.0.289), Inspirations(0.2.4), Mantle (1.3.3.55)

**Comment by KnightMiner** [comment]
Fixed in 0.2.5
