### ISSUE TITLE
Support for Rockhounding Ore Tiers Smouldering Coal Deposit

### ISSUE THREAD

**Issue by WenXin20** [KnightMiner/Inspirations#132]
Minecraft 1.12.2
Forge v14.23.5.2838
Inspirations v0.2.5
[Rockhounding Ore Tiers](https://www.curseforge.com/minecraft/mc-mods/rockhounding-mod-ore-tiers) v3.10

Rockhounding has a block called Smouldering Coal Deposit. The JEI block description for it says that it can be converted to a normal coal block by using it on a filled cauldron, but there seems to be a compatibility issue with this mod.

**Comment by KnightMiner** [comment]
As a workaround, you can add it to the cauldron config as a normal recipe. I will have to look into the best way to handle not overriding that by default though.

**Comment by WenXin20** [comment]
Ok, thanks. I didn't realize there was a config for cauldron recipes.

**Comment by KnightMiner** [comment]
Closing this as I have dropped 1.12 support. 1.16 added a feature where you could tag items via datapack to bypass my cauldron logic, but 1.12 never got such a feature backported, so adding your own recipes is probably your best bet.
