### ISSUE TITLE
Sugar cane seeds and right-click harvesting

### ISSUE THREAD

**Issue by WenXin20** [KnightMiner/Inspirations#134]
Minecraft v1.12.2
Forge v14.23.5.2838
Inspirations v0.2.5
[Quark](https://www.curseforge.com/minecraft/mc-mods/quark) r1.5-168

If I right-click sugar cane two or three blocks up from the ground, the seed gets replanted on top of the sugar cane block.
Quark is the mod I'm using for right-click harvesting.

**Comment by WenXin20** [comment]
If this needs to be reported to Quark, I can do that as well.

**Comment by KnightMiner** [comment]
Can you post a screenshot to show what you mean? This sounds odd to say the least

**Comment by WenXin20** [comment]
The sugar cane seed got planted on top of the sugar cane plant.
![2019-07-15_19 41 26](https://user-images.githubusercontent.com/12000593/61257885-91584880-a738-11e9-956b-e275ff7dd183.png)

**Comment by KnightMiner** [comment]
Fixed in latest Quark
