### ISSUE TITLE
Fluids won't push into cauldron

### ISSUE THREAD

**Issue by IronPiston** [KnightMiner/Inspirations#135]
According to [this](https://github.com/KnightMiner/Inspirations/issues/71), cauldrons should support fluid input. However, attaching a fluiduct from Thermal Dynamics to every face of the cauldron fails to fill it.

![2019-07-20_15 50 31](https://user-images.githubusercontent.com/11603684/61584014-51151380-ab06-11e9-93ca-2f66532b8e2f.png)

**Comment by KnightMiner** [comment]
They do support fluid input, but you must do so in 1 bucket increments (or 250mb if bigger cauldrons is enabled). Nothing I can do to make it less strict, try using better fluid pipes or use the dispenser option.
