### ISSUE TITLE
Lava in cauldrons doesn't burn items

### ISSUE THREAD

**Issue by zauberparacelsus** [KnightMiner/Inspirations#137]
Tossing an item into lava normally burns and destroys it, but tossing an item into a lava-filled cauldron does nothing.

**Comment by KnightMiner** [comment]
This is intentional, tossing items into a cauldron (using a dropper for instance) is the way to automatically perform cauldron recipes, you would not want your item to be destroyed simply because you dropped it in a bit too soon.
