### ISSUE TITLE
Couple of minor spelling/grammar errors on the wiki.

### ISSUE THREAD

**Issue by WorkInProgress-Development** [KnightMiner/Inspirations#139]
Maybe this is overdoing it, but I've found some issues with the wiki pages for this repository (https://github.com/KnightMiner/Inspirations/wiki).

- On the main page (https://github.com/KnightMiner/Inspirations/wiki), it reads

> Currently, the mod is divided into four main modules:

and should be _Currently, the mod is divided into **five** main modules:_

- Bookselves should be bookshelves (https://github.com/KnightMiner/Inspirations/wiki/Building-Module)
- On the main page (https://github.com/KnightMiner/Inspirations/wiki/Utility-Module), it reads
> Additionally, it is highly sensitive to redstone changes, meaning if it receives redstone power on any side it will toggle it's state. 

and should be _Additionally, it is highly sensitive to redstone changes, meaning if it receives redstone power on any side it will toggle **its** state._

Again, sorry if this is more annoying than useful. Also, I would do a pull request, except it seems you can't pull request a wiki edit.

**Comment by KnightMiner** [comment]
Fixed the wiki pages
