### ISSUE TITLE
[Suggestion] Better Hopper Item Model

### ISSUE THREAD

**Issue by CuChulainn0** [KnightMiner/Inspirations#143]
It may sound kind of silly, but I'd like to see the hopper item model receive the same treatment as the cauldron item model, i.e. using the 3D model instead of the terrible 2D sprite. It would be extra nice if this could extend to the Tinkers wooden hopper as well, but I don't want to sound too demanding.

**Comment by TeamSpen210** [comment]
You can actually do this with a resource pack, no mod required.

**Comment by KnightMiner** [comment]
Yeah, doubt I will do that in Inspirations since its so easy to do in a resource pack. Mainly did cauldrons since I made so many cauldron changes, including one that changed the model.
