### ISSUE TITLE
bookshelf=false F3+T crash?

### ISSUE THREAD

**Issue by freecsu** [KnightMiner/Inspirations#145]
My Minecraft client stops responding indefinitely (but doesn't fully crash) anytime I press F3+T (to fix the no sound bug) and I narrowed down the issue to my mod configs, then further narrowed it down to inspirations.cfg, specifically the line:
```
    # Enables the bookshelf: a decorative block to display books [default: true]
    B:bookshelf=false
```
With that set to false the issue is reproducible every time and absent when it is set to true. The only other non-default setting in my inspirations config is rope=false which does not cause any issues on its own.

Here is my entire modlist, I suspect this issue has to do with an interaction between inspirations and another mod or else I wouldn't be the first one to spot this.

![](https://i.imgur.com/vVz2h2g.png)

**Comment by KnightMiner** [comment]
I cannot reproduce this, can you post your full game log? That would help me look into the issue.

**Comment by KnightMiner** [comment]
Closing for lack of response
