### ISSUE TITLE
Issues with enchanted shields

### ISSUE THREAD

**Issue by Tohricat** [KnightMiner/Inspirations#146]
The knockback enchantment doesn't seem to affect players, only mobs. Also, the 'enchanting glow/sheen' doesn't show up on the shield model.

**Comment by KnightMiner** [comment]
Enchanted glow is actually a Mojang decision/ommission, and one I do not intend to change. Gets in the way of the banner patterns.

I thought I had knockback working on players, but it's very hard to test, I'll have to look into it again, but not sure if I'll do another 1.12 release at this point

**Comment by KnightMiner** [comment]
Fixed in 0.2.9
