### ISSUE TITLE
possible suggestion

### ISSUE THREAD

**Issue by EternalOne11** [KnightMiner/Inspirations#147]
https://www.curseforge.com/minecraft/mc-mods/visible-armor-slots
I think this would be a nice feature in the mod although I'm guessing that you are not interested in it. You may close this if you want just want you to possibly consider it thats all.

**Comment by KnightMiner** [comment]
I cannot see myself adding this feature as a mod already exists for it. I doubt it would be that difficult for someone to port the existing mod (I may even do it myself if I ever have free time again)

**Comment by EternalOne11** [comment]
ok
