### ISSUE TITLE
(Suggestion) time based cauldron recipes (fluid -> fluid)

### ISSUE THREAD

**Issue by inkdear** [KnightMiner/Inspirations#149]
I'm not sure if this is something that would be in keeping with the Inspirations cauldron or not, but here it is anyway: the ability to define cauldron recipes that require a fluid to sit in the cauldron for a certain amount of time (heated or unheated.) Could be used to boil fluids into other fluids, allow fluids to cool/set, age, etc.

It would also be extremely neat if it could do the old ex nihilo thing of block -> fluid (and vice versa.) 

I would suggest the ability to include time as a factor in fluid + items = fluid recipes, but I assume this is omitted by design.

**Comment by KnightMiner** [comment]
This is something I would like to add, but not sure how I want to go about doing it. It will definately be in the 1.14 rewrite if added anywhere. I have added this to the redesign notes as a consideration, so I'll close this issue
