### ISSUE TITLE
BlockColors crash if another mod has an error

### ISSUE THREAD

**Issue by WenXin20** [KnightMiner/Inspirations#152]
**Describe the bug:**

- If another mod has an error, such as with an invalid config file, Inspirations will crash instead of displaying the forge error screen and what went wrong with the other mod. 
- This could mislead the player into thinking Inspirations is at fault instead of something else.

**Versions:**

* `Minecraft: v1.14.4`
* `Forge: v28.1.109`
* `Mantle: v1.4.32`
* `Inspirations: v1.0.2`

**Attachments**

[Crash Report](https://gist.github.com/WenXin20/d3cbfc60bbe1e407d2e7868ce852cadc)

**Comment by KnightMiner** [comment]
Yeah, this is a Forge bug, see MinecraftForge/MinecraftForge#5862. There is not a ton I can do about it as if its not block colors that crashes, its going to be something else later.

I suppose I can add null checks like I had in 1.12, but that will just bounce the issue to the next mod registering block colors, or perhaps the Forge event following block colors.

**Comment by WenXin20** [comment]
Adding null checks would be nice, it took me pretty much all day to figure out which mod was actually crashing. I had to remove all the mods that were giving me blockColor crashes.

**Comment by KnightMiner** [comment]
Whenever you see a block colors crash, your best bet right now is the full game logs. Normally the actual exception is logged before block colors crashes.

**Comment by WenXin20** [comment]
That's what I checked first, but unfortunately, it was a crash between 2 other mods, but the logs only pointed to one of those mods. It all figured out now though.

**Comment by KnightMiner** [comment]
Latest Forge issue is MinecraftForge/MinecraftForge#6374 for my reference

**Comment by KnightMiner** [comment]
Mostly caught, whats not caught Forge has dealt with, so closing
