### ISSUE TITLE
customPortalColor conflicting with Aether Legacy and/or BetterPortals

### ISSUE THREAD

**Issue by Peavii** [KnightMiner/Inspirations#154]
**Describe the bug:** Placing the water to create the Aether legacy portal causes a freeze, then Minecraft crashes. I found in my VanillaFix crash report that it was probably customPortalColor=true causing the crash. I find this recreatable every 1 out of ~4 attempts to finish an Aether portal. 

**Versions:** 
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.5.2847-win
* Mantle: Mantle-1.12-1.3.3.55
* Inspirations: Inspirations-1.12.2-0.2.9

**Other mods required:**
* BetterPortals: betterportals-0.3.7.4  (_Maybe_)
* The Aether: aether_legacy-1.12.2-v1.4.4

**Attachments**
VanillaFix Crash Report: https://paste.dimdev.org/bulimucejo.mccrash

**Comment by KnightMiner** [comment]
Hmm, looks like Aether created a client world that has no renderGlobal. Its pretty easy for me to catch this, so if I end up doing another 1.12 build it will be fixed

**Comment by KnightMiner** [comment]
Going to close this as I have no plans to make more 1.12 builds, I have way to many mods to support each on two versions. So unfortunately you will have to disable that feature if you want to play with Aether Legacy
