### ISSUE TITLE
Add waterloggable state to blocks

### ISSUE THREAD

**Issue by WenXin20** [KnightMiner/Inspirations#155]
**What is the feature requesting?**

- Add the waterloggable state to non-full blocks.

**Why should this feature be added?**

- Waterlogging of blocks could add many more decoration options to the game and add more immersion, such as with pipes, paths, ropes, chains, bookshelves, etc.

**Versions:**
* Minecraft: v1.14.4
* Inspirations: v1.0.2

**Comment by KnightMiner** [comment]
Ropes and chains already can be waterlogged. Pipes will be as well in an upcoming release.

I think paths makes a lot of sense, not sure on bookshelves, but I noted both on TODO list to look into.
