### ISSUE TITLE
Light Gray Items Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [KnightMiner/Inspirations#156]
**Describe the bug:**

The Light Gray Book & Carpeted Trapdoor is missing localization. 
They show up as `item.inspirations.light_gray_book` and `item.inspirations.light_gray_carpeted_trapdoor`.

**Versions:**

* Minecraft: v1.14.4
* Forge: v28.1.90
* Mantle: v1.4.32
* Inspirations: v1.0.2

**Comment by KnightMiner** [comment]
Already fixed in bae0cfd, just not released yet.

**Comment by KnightMiner** [comment]
Fixed in release 1.1.0 for 1.15.2. I do not currently plan to continue 1.14 updates, as many mods are skipping that version.
