### ISSUE TITLE
Suggestion: Pipe Facades

### ISSUE THREAD

**Issue by SuiguraTaiki** [KnightMiner/Inspirations#157]
**What is the feature requesting?**
Pipe Facades, a.k.a. a way to hide your pipes.

**Why should this feature be added?**

A way to cosmetically hide Pipe systems within the same block as they occupy, as well as making their hitbox occupy the whole block. Even though it is a niche case where this would be required, it would be both very useful for larger contraptions and an appealing addition

**Versions:**
* Minecraft: 1.14.4
* Inspirations:

**Comment by KnightMiner** [comment]
No, this does not fit in the mod. Inspirations is designed to add features which would fit in vanilla, and facades have never fit well in my opinion. Part of the challenge in redstone is not every block is super compact, so its your job to compact it.
