### ISSUE TITLE
Player HP heart mark color changes could be configured?

### ISSUE THREAD

**Issue by feru4g** [KnightMiner/Inspirations#159]
**What is the feature requesting?**

Please could you implement configuration "PC HP Color Change" mode ( or deffault).

**Why should this feature be added?**

When HP is over 20, that color changes red to orange, to yellow.
I noticed bad-effect attack with it (green, black), so color change is a little shocked and confused for a short time.
I am very pleased with almost your MOD contents, hope consider this matter.

**Versions:**
* Minecraft: 1.14.4
* Inspirations: 

**Attachments**

**Comment by KnightMiner** [comment]
This is not an Inspirations feature, it comes from Mantle.
