### ISSUE TITLE
java.lang.NullPointerException: Initializing game [...] at knightminer.inspirations.building.BuildingClientProxy.registerItemColors(BuildingClientProxy.java:132) ~[?:1.14.4-1.0.2] {re:classloading}

### ISSUE THREAD

**Issue by Spooqi-Software** [KnightMiner/Inspirations#160]
**Describe the bug:**

Crashing upon launch, apparently during registration of item colors.

**Versions:**

* Minecraft: 1.14.4
* Forge: 28.2.4
* Mantle: 1.4.32
* Inspirations: 1.0.2

**Other mods required:**

Unknown if related to mod compatibility - but mod pack is quite large (see crash report for mod list)

**Attachments**

[crash-2020-04-23_03.10.33-client.txt](https://github.com/KnightMiner/Inspirations/files/4520822/crash-2020-04-23_03.10.33-client.txt)

**Comment by KnightMiner** [comment]
Post your full game log. This crash is caused by another mod breaking something during initialization. Forge instead of showing the useful crash decides to continue trying to register stuff when it never registered blocks.

**Comment by KnightMiner** [comment]
Closing for lack of response. Duplicate of #152 for the record.
