### ISSUE TITLE
1.12 - Minor conflict with Chisel mod

### ISSUE THREAD

**Issue by tgevrenos** [KnightMiner/Inspirations#161]
The mod somewhat removes the chisel recipe for the chiseled carpets. The carpets do exist in game but for some reason when you try to chisel a carpet, the chiseled ones do not show. (What i did for now was to create custom recipes for the ones I use.)

After I disable "inspirations" chisel seems to work fine. (I am hoping a compatibility could be worked out.)

Please refer to the screenshot below & original post created:
[https://github.com/Chisel-Team/Chisel/issues/828](url)

**Versions:**

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Mantle: 1.3.3.55
* Inspirations: 1.12.2 - 0.2.9

* Chisel: MC1.12.2 - 1.0.2.45

<img width="2560" alt="80391073-ee7f4e00-88b5-11ea-9c3a-3ad802ae0186" src="https://user-images.githubusercontent.com/43979665/81047417-03b23900-8ec3-11ea-919e-292786963138.png">

**Comment by TeamSpen210** [comment]
Inspirations does replace the carpet block, to allow them to conform to the shape of stairs below. If you disable that feature Chisel would work again. Fixing the issue properly needs to be done on Chisel’s side, by not using the static reference.

**Comment by KnightMiner** [comment]
Closing this as I am dropping 1.12 support. For 1.16 hopefully Chisel will not have this problem
