### ISSUE TITLE
Server Crash with Quark mod

### ISSUE THREAD

**Issue by FuryOfFools** [KnightMiner/Inspirations#164]
Describe the bug:
Server Crashed with Quark mod

Crash report:
[crash-2020-05-12_19.22.24-server.txt](https://github.com/KnightMiner/Inspirations/files/4616523/crash-2020-05-12_19.22.24-server.txt)

Versions:
 - Minecraft: 1.15.2
 - Mantle: 1.5.15
 - Inspirations 1.1.0

Other mods required:
AutoRegLib-1.5-40
Quark-r2.1-235

**Comment by Partonetrain** [comment]
This was fixed on Quark's end

**Comment by FuryOfFools** [comment]
@Partonetrain wow. Unexpectedly yes

**Comment by KnightMiner** [comment]
Oh good, nice for an issue to be fixed before I even see it. Crosslinking Vazkii/Quark#2140 for future reference.
