### ISSUE TITLE
Mulch does not have a recipe

### ISSUE THREAD

**Issue by stop-x13** [KnightMiner/Inspirations#165]
**Describe the bug**
There isn’t a recipe for mulch though the wiki and config say it is craftable.

**Screenshots

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.5.15
 - Inspirations: 1.1.0

**Other mods required**

I don’t think other mods change this because mulch.json simply doesn’t exist.

**Comment by KnightMiner** [comment]
Mulch recipe was changed to use the stone cutter, however it does not show in JEI at this time. Can you please test to see if putting planks in a stone cutter still works?

**Comment by KnightMiner** [comment]
I double checked, and it looks like JEI should have support in the latest 1.15 Alpha build, see https://www.curseforge.com/minecraft/mc-mods/jei/files/2944279. It should be in a release shortly.

**Comment by KnightMiner** [comment]
Closing as the latest JEI alpha has the ability to view stonecutter recipes.
