### ISSUE TITLE
Dispenser Recipe Uses 3 Droppers in a Column

### ISSUE THREAD

**Issue by stop-x13** [KnightMiner/Inspirations#166]
**Describe the bug**
It should be 1 dropper instead, plus 3 sticks.

**Screenshots or crash report (if relevant)**

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Inspirations: 1.1.0

**Comment by KnightMiner** [comment]
Huh, that is interesting. Wonder how that happened. For my future reference, this is the stackable dispenser recipe.

**Comment by KnightMiner** [comment]
Fixed in 1.2.0
