### ISSUE TITLE
better config

### ISSUE THREAD

**Issue by EternalOne11** [KnightMiner/Inspirations#167]
I would like a better config like the 1.12.2 version.

The config for this version is about each individual modules but many people prefer being able to disable each individual feature. for example, I want the flower variants but not the decorated leaves. 

If you cant let me know If I can ask on the requests section of the MMD discord.

**Comment by KnightMiner** [comment]
You can do this, it's a server config. This means the config options exist per world instead of globally. There is a forge feature to set default server config options for the sake of modpacks.
