### ISSUE TITLE
Sugar Canes and Enchanted Book Texture/Rendering? Bug

### ISSUE THREAD

**Issue by Leirday** [KnightMiner/Inspirations#168]
**Describe the bug**
Whenever I have the Inspirations Mod installed, Sugar Cane tends to have a weird rendering issue when it grows. Also, the Enchanted Book's texture seems to not change even if there is a texture pack that is supposed to make it look different!

**Screenshots or crash report (if relevant)**
Inspirations Mod Not Installed
![2020-05-14_21 39 51](https://user-images.githubusercontent.com/63563648/82003126-91152c00-962d-11ea-9320-81db51a16de3.png)

Inspirations Mod Installed:
![2020-05-14_21 51 11](https://user-images.githubusercontent.com/63563648/82003478-74c5bf00-962e-11ea-9209-cc19bdb5e7df.png)

![2020-05-14_21 53 07](https://user-images.githubusercontent.com/63563648/82003514-8d35d980-962e-11ea-9d93-f4d1a39a3a96.png)
![2020-05-14_21 51 22](https://user-images.githubusercontent.com/63563648/82003883-80fe4c00-962f-11ea-8f2f-e050a628784b.png)

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.15.2-1.5.15
 - Inspirations 1.15.2-1.1.0

![Uploading 2020-05-14_21.51.11.png…]()

Note: GitHub doesn't let me upload the screenshot of the Enchanted Book (Inspirations Not Installed), also, the texturepack is called Simplistico.

**Comment by KnightMiner** [comment]
What you are looking at is a lack of resource pack support for two of my features. I replace the enchanted book texture in order to recolor the book ribbons based on the enchantements, and make sugar cane grow smoothly (pixel by pixel) instead of in full blocks. It is easy for resource packs to support my feature, or you can just disable the two features in my config.

**Comment by Leirday** [comment]
> What you are looking at is a lack of resource pack support for two of my features. I replace the enchanted book texture in order to recolor the book ribbons based on the enchantements, and make sugar cane grow smoothly (pixel by pixel) instead of in full blocks. It is easy for resource packs to support my feature, or you can just disable the two features in my config.

Oh, thanks for the help. However, I can't find the features on the config file. Is there a place where I can check where they are located in?

Edit: Found the Enchanted Book one; still looking for the sugar cane file. :/
Edit #2: It seems I edited the file for the 1.12.2 version of Inspirations because it did not change anything on the game itself. I tried other files and whenever I deactivate the "Tweaks" file the mod fails to load. I'm going to deinstall the mod until it gets another update or when it gets fully released because it seems it isn't complete yet; which is something I fully understand due to it being in Alpha.

**Comment by KnightMiner** [comment]
By fails to load, do you mean crashes? If so, post the crash report in another issue.

As far as config, the sugar cane feature is part of the serverside config, which is saved per world. I suggest researching Forge default configs. The other one you found was in the client side config, which can be different per user.

**Comment by Leirday** [comment]
> By fails to load, do you mean crashes? If so, post the crash report in another issue.
> 
> As far as config, the sugar cane feature is part of the serverside config, which is saved per world. I suggest researching Forge default configs. The other one you found was in the client side config, which can be different per user.

Yes, after all the mods have been loaded, a screen appears saying that the mod failed to load. Here is the screenshot:

![Base Profile Screenshot 2020 05 15 - 11 45 17 92](https://user-images.githubusercontent.com/63563648/82069765-cc514280-96a1-11ea-8d12-90ae42e9f2eb.png)

**Comment by KnightMiner** [comment]
Locate either a relevant crash report or your latest.log and post it on a new issue. Pastebin will let you upload it easily
