### ISSUE TITLE
Failed to load whenever the "Tweaks" Module is set to "False".

### ISSUE THREAD

**Issue by Leirday** [KnightMiner/Inspirations#169]
**Describe the bug**
The mod fails to load whenever the Tweaks Module has been set to false.

**Screenshots or crash report (if relevant)**
![Base Profile Screenshot 2020 05 15 - 11 45 17 92](https://user-images.githubusercontent.com/63563648/82079788-71bfe280-96b1-11ea-9835-eed3a80a0e08.png)
[latest.log](https://github.com/KnightMiner/Inspirations/files/4636111/latest.log)

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.15.2-1.5.15
 - Inspirations 1.15.2-1.1.0

**Comment by DamienBrittan** [comment]
Same here .

**Comment by KnightMiner** [comment]
The module system in Mantle was pretty broken in 1.15 as it violated one of the new Forge standards. This is fixed for 1.16 by switching to a simpler module system, but I probably will not backport the change to 1.15 (its quite extensive). So if you want to disable a module, use 1.16
