### ISSUE TITLE
Inspirations is not compatible with Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by Leirday** [KnightMiner/Inspirations#170]
**Describe the bug**
Whenever I have the Inspirations Mod installed, the Cosmetic Armor Reworked Mod's armor icon on the inventory stops working properly and it doesn't allow me to access the "show/hide armor menu." I have tried testing this with disabling certain modules but it doesn't seem to fix the problem. It requires further testing in my opinion.

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.15.2-1.5.15
 - Inspirations 1.15.2-1.1.0
 - Cosmetic Armor Reworked: CosmeticArmorReworked-1.15.2-v3a.jar

**Comment by KnightMiner** [comment]
Does this happen with just the two mods? And can you post your latest.log so I can check for errors?

**Comment by Leirday** [comment]
> Does this happen with just the two mods? And can you post your latest.log so I can check for errors?

The game doesn't crash so I can't show you the latest.log :/ 
What I reported on the Issue is that the mods don't seem to be compatible.

**Comment by KnightMiner** [comment]
The latest.log is created whether there is a crash or not. Crash reports only exist when there is a crash. Try looking in your logs folder.

And you did not answer my question. Have you tested with **only** the two mods, and no other mods installed? I know they seem to be incompatible, but there may be another mod causing problems

**Comment by Leirday** [comment]
> The latest.log is created whether there is a crash or not. Crash reports only exist when there is a crash. Try looking in your logs folder.
> 
> And you did not answer my question. Have you tested with **only** the two mods, and no other mods installed? I know they seem to be incompatible, but there may be another mod causing problems

[latest.log](https://github.com/KnightMiner/Inspirations/files/4653064/latest.log)
Answer to your question: I went back into my world (the one where I discovered the issue) and the menu from the Cosmetic Armor Reworked seems to be working again. I'm going to try this with only both mods installed to see if it's them or if its another mod that caused the issue.

**Comment by KnightMiner** [comment]
Your log has a lot of exceptions caused by Optifine. While I have no experience with the 1.15 version, the 1.12 version was known to break much of rendering including UI. Try testing without that as well

**Comment by DamienBrittan** [comment]
Works well for me .

**Comment by KnightMiner** [comment]
Closing for lack of response, and other users say it work. Personally blaming Optifine as it always breaks even my simplest custom renderers.
