### ISSUE TITLE
Inspirations + Survive = Crash

### ISSUE THREAD

**Issue by SissyTrashQueen** [KnightMiner/Inspirations#171]
**Versions:**
Minecraft:1.15.2
Forge: 31.2.0
Inspirations 1.1.0 for 1.15.2

**Describe the bug**

Survive-1.15.2-1.5.0  -Added the ability to drink water from cauldrons
The game crashes when loading up.

[**Crash report**](https://gist.github.com/slard3/b1d824bcd28fab4e279fab6bf5d838d3)

Sadly, the mod dev of Survive hasn't disclosed their source

**Comment by KnightMiner** [comment]
Please post your full game log, the real crash cause is hidden due to a Forge bug.

**Comment by SissyTrashQueen** [comment]
Oh, sorry, didn't know, hope this helps!
[Logs](https://gist.github.com/slard3/4c12fe735b07a22ece731109371ed3b3)

**Comment by KnightMiner** [comment]
Yep, found what I was looking for there:

```
Failed to register automatic subscribers. ModID: survive, class com.stereowalker.survive.Survive
java.lang.NoClassDefFoundError: com/stereowalker/unionlib/util/ScreenHelper$ScreenOffset
```

Looks like a Survive bug, Inspirations just happened to get included in the stack trace because of the dumb Forge bug. I can add a safety there just so I stop getting blamed for all these exceptions though.

See #152 for more info on that

**Comment by SissyTrashQueen** [comment]
I guess I'll make an issue on Survive's side then, thanks for looking into this! :)
