### ISSUE TITLE
Is this a bug, or not implemented yet?

### ISSUE THREAD

**Issue by Rithenar** [KnightMiner/Inspirations#174]
**Describe the bug**
When using an enchantment book from another mod (i.e. Apotheosis), and the book has 2 enchantments that apply to different items, the anvil will only apply the enchantment that corresponds to that tool.  The Inspiration enchantment book, however, does not do that.

**Screenshots or crash report (if relevant)**
Here you see the Miner's Fervor being applied to the pickaxe even though the book also has Mounted Strike as you can see next screenshot
![Ench to pick](https://user-images.githubusercontent.com/9939332/87312859-bd8edc80-c4e6-11ea-8143-4bf4e972c089.png)
Here are the Apotheosis book enchantments
![ench book apotheosis](https://user-images.githubusercontent.com/9939332/87312267-f11d3700-c4e5-11ea-8324-8f4140508abf.png)
Here you will see nothing will apply to the pick with the Inspirations book
![ench to pick X](https://user-images.githubusercontent.com/9939332/87312889-ca133500-c4e6-11ea-9292-e14ecd529449.png)

Here are the enchantments from the book
![inspirations ench book](https://user-images.githubusercontent.com/9939332/87312277-f5495480-c4e5-11ea-82a1-7693a54b926b.png)

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.15.2-1.5.15
 - Inspirations 1.15.2-1.1.0

**Other mods required**

This happens while playing the Ferrous Block modpack

EDIT:  I also tried with an Obsidian level pickaxe (diamond)

**Comment by KnightMiner** [comment]
All I change about the enchanted book is the model, client side only display. None of my changes could affect anvil behavior as they are solely visual. Test with fewer mods so you can narrow down which mod is to blame.

**Comment by Rithenar** [comment]
You are right KnightMiner, sorry to bother you with this. I believe the issue is with Ma Enchants and not Inspirations.
