### ISSUE TITLE
Seeds from Cactus and Sugar Cane

### ISSUE THREAD

**Issue by Rithenar** [KnightMiner/Inspirations#175]
**Describe the bug**
Is the Cactus and Sugar Cane's behavior being similar to the potatoes and carrots something actually intended?  Sugar Cane and Cactus usually don't grow like potatoes and carrots as they update a whole block on top of the previous at the same time, instead of slowly growing a % . Right now, as they grow in stages it means that if you try to automate a farm with pistons, you only get seeds.

Also, when you look at the growing cactus, The One Probe shows it as Wheat Seeds (see screenshot) 

**Screenshots or crash report (if relevant)**

![image](https://user-images.githubusercontent.com/9939332/87482684-8d832e80-c5f7-11ea-934d-cea517e99f32.png)

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.15.2-1.5.15
 - Inspirations 1.15.2-1.1.0

**Other mods required**

List any other mods required to reproduce this issue. Test by running the game with minimal mods.

**Comment by KnightMiner** [comment]
Look at the config file, it has an option to disable the smooth growth or to just prevent it from breaking classic cactus farms. This is an intentional feature.

Not sure why it shows as wheat seeds, probably some method that needs overriding. I may have already fix it.

**Comment by Rithenar** [comment]
Oh great! Thanks for the quick response.  I will do that.
