### ISSUE TITLE
Request/Advice: FluidRecipe that doesn't consume input item

### ISSUE THREAD

**Issue by Echoweaver** [KnightMiner/Inspirations#176]
I am trying to make a (somewhat silly) butter churn recipe for the cauldron using ModTweaker. The idea is that I fill the cauldron with milk and then use a stick on it to get Harvestcraft butter. The stick may be a standin for a custom item if I get the momentum to model something.

The problem is that I haven't been able to keep the stick from being consumed. I can see this as being something other folks might want to do with a cauldron -- use a spoon to stir or a magic wand to transform something.

Since the input for a fluid recipe is IIngredient, I tried using a .reuse transform method on the stick, but that doesn't seem to work.

Is this sort of thing supported? If not, would you consider adding support?

**Comment by KnightMiner** [comment]
I have stopped 1.12 development., hence why there was no 1.12 feature request template. If you want to put in the effort, my API would allow you to implement a recipe as you described. I just never found the craft tweaker syntax free enough to support adding that (only so many optional parameters make sense, and I already had so many variants)

**Comment by Echoweaver** [comment]
Well, I'll be danged. Just setting input stack to 0 worked. 

`mods.inspirations.Cauldron.addFluidRecipe(<harvestcraft:butteritem>, <minecraft:stick>* 0, <liquid:milk>, 1);`

**Comment by KnightMiner** [comment]
Uh, that shouldn't work, but I guess that is better than nothing.
