### ISSUE TITLE
Texture Tweaks Incompatible with Optifine 1.16

### ISSUE THREAD

**Issue by GabeVXIX** [KnightMiner/Inspirations#177]
As the title says, textures are glitching when combined with Optifine.
When Optifine is installed, the portal colors, firework colors, cauldron model, and enchanted book colors don't show up, instead replaced with the "missing texture" pink and black grid. Obviously 1.16 and the newest Optifine update are very recent and still being updated, but I really like these additions so if there are any possible compatibility changes it would be really helpful.

![2020-08-08_15 51 22](https://user-images.githubusercontent.com/69402804/89719582-771a8980-d98f-11ea-8fba-de08cf471392.png)
![2020-08-08_15 51 25](https://user-images.githubusercontent.com/69402804/89719583-77b32000-d98f-11ea-96ad-ac7e30a7c491.png)
![2020-08-08_15 51 27](https://user-images.githubusercontent.com/69402804/89719584-77b32000-d98f-11ea-84fe-275ce0d19e00.png)
![2020-08-08_15 51 36](https://user-images.githubusercontent.com/69402804/89719585-77b32000-d98f-11ea-9081-866e90c4a256.png)
![2020-08-08_15 51 16](https://user-images.githubusercontent.com/69402804/89719586-784bb680-d98f-11ea-92c2-6d363895d948.png)

Versions:
 - Minecraft: Forge 1.16.1-32.0.107
 - Mantle: Alpha 1.16.1-1.16.20
 - Inspirations: 1.2.0 for 1.16.1

This issue only happens when Inspirations is combined with OptiFine. I've tried changing lighting, texture, and shader settings introduced by OptiFine, but nothing works. Hope this helps!

**Comment by KnightMiner** [comment]
Looks like Optifine is yet again breaking Forge rendering. It is an absolute pain to attempt to debug rendering with Optifine, but I will tell you they outright replace large sections of Forge rendering code with their own, so breaks are almost unavoidable.

I have some planned changes in the future that may fix this, but until Optifine is coded in a way that does not destroy any hope of using Forge rendering, I will not directly support it. I suggest you use another performance enhancing/graphics mod.
