### ISSUE TITLE
Minecraft freezes when reloading textures and missing textures

### ISSUE THREAD

**Issue by TimestaticYT** [KnightMiner/Inspirations#178]
**Describe the bug**
I have this problem when I just launch Forge version 1.16.1-32.0.108 with optifine, inspirations and mantel it freezes every time I try any sorts of reloading the textures (shaders,recourcepack,reloading textures manually etc.) and the texture of cauldrons different enchantet books and fireworks for example are missing. Without Optifine everything works fine but it sucks that they dont work together for me right now

**Screenshots or crash report (if relevant)**
Here i manually reloaded the resources but when I try to turn shaders on it also gives this info in the crash report:
[OptiFine] Unknown resource pack file: mod_resources

---crash report---
[m[32m[16:06:45] [Render thread/INFO] [ne.op.Config/]: [OptiFine] *** Reloading custom textures ***
16:06:45.121
[m[33m[16:06:45] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources
16:06:45.134
[m[33m[16:06:45] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources
16:06:45.134
[m[33m[16:06:45] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources
16:06:47.993
[m[33m[16:06:47] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources
16:06:48.036
[m[33m[16:06:48] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources
16:06:48.037
[m[33m[16:06:48] [Render thread/WARN] [ne.op.Config/]: [OptiFine] Unknown resource pack file: mod_resources
16:06:48.037
[m[32m[16:06:48] [Render thread/INFO] [ne.op.Config/]: [OptiFine] Disable Forge light pipeline
16:06:48.037
[m[32m[16:06:48] [Render thread/INFO] [ne.op.Log/]: [OptiFine] Set ForgeConfig.CLIENT.forgeLightPipelineEnabled=false

**Versions (please complete the following information):**
 - Minecraft: 1.16.1-forge-32.0.108
 - Mantle: Mantle-1.16.1-1.6.27
 - Inspirations: Inspirations-1.16.1-1.2.0

**Other mods required**
-OptiFine_1.16.1_HD_U_G2
List any other mods required to reproduce this issue. Test by running the game with minimal mods.

**Comment by KnightMiner** [comment]
Your crash says clearly Optifine is to blame. I do not support Optifine as no matter what I do, no matter how simple, it breaks my stuff. They do that by outright replacing major forge systems. Specifically, Optifine seems to have broken the system Forge uses to add mod resources. Obviously this will not work, and there is nothing I can do to fix that.
