### ISSUE TITLE
Sugar cane growth mislabeled in waila/etc

### ISSUE THREAD

**Issue by Xetaxheb** [KnightMiner/Inspirations#179]
**Describe the bug**
Sugar cane growth hwyla/waila's as cactus seeds but drops sugar cane seeds as intended
Similar/related to #175 maybe?

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Mantle: Mantle-1.16.1-1.6.27.jar
 - Inspirations: Inspirations-1.16.1-1.2.0.jar

**Comment by KnightMiner** [comment]
Fixed in 1.2.1.23
