### ISSUE TITLE
Glass doors are missing the doors tag

### ISSUE THREAD

**Issue by WenXin20** [KnightMiner/Inspirations#181]
**Describe the bug**

The Glass Door is missing the `#minecraft:doors` tag, which means villagers cannot open the door.

**Versions:**
 - `Minecraft: v1.15.2`
 - `Mantle: v1.5.15`
 - `Inspirations: v1.1.0`

**Comment by KnightMiner** [comment]
Will be fixed in next 1.16 build, probably won't backport to 1.15

**Comment by WenXin20** [comment]
Alright, thanks!

**Comment by KnightMiner** [comment]
Fixed in 1.2.1.23
