### ISSUE TITLE
Nether Portal Missing Texture

### ISSUE THREAD

**Issue by glytch-g** [KnightMiner/Inspirations#182]
**Describe the bug**
The mod for some reason causes the texture for the nether portal to become "missing." Took out all my mods to pinpoint the issue. Eventually found out this mod was causing it. Tried no Resource and Shader packs, messing with graphics, removing optifine, clean install etc. When this mod is not installed, the issue is not present. The 'purple' semi opaque portion of the portal and particle effects turns into the black/pink missing texture. It is present in the overworld and nether. Issue is consistent with glass underneath the portal and no glass and any size nether portal.

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Mantle: Mantle-1.16.1-1.6.27
 - Inspirations: Inspirations 1.2.0 for 1.16.1

**Other mods required**
Forge (any version but I was running forge-1.16.1-32.0.108. 

Thank you!

**Comment by KnightMiner** [comment]
Does this happen with just Inspirations, and no other mods installed? I have seen this type of missing texture error before, and its almost always caused by another mod changing model loading. Notably, do you have any performance enhancing mods, such as the unofficial ports of those two Fabric performance enhancing mods?

**Comment by glytch-g** [comment]
This is my mod list at the time of installation. I do not believe any of them are performance enhancing mods. I can tinker with it and let you know if it happens with just Inspirations.

|   Abnormals-Core-1.16.1-2.0.4.jar
|   AmbientSounds_v3.0.20_mc1.16.2.jar
|   Atmospheric-1.16.1-2.0.0.jar
|   AutoRegLib-1.6-43.jar
|   Autumnity-1.16.1-1.4.1.jar
|   BetterCaves-1.16.1-1.0.jar
|   BetterMineshaftsForge-1.16.1-1.3.jar
|   BiomesOPlenty-1.16.1-11.0.0.396-universal.jar
|   Bones-1.16.1-1.3.2.jar
|   Bookshelf-1.16.1-6.3.21.jar
|   Botania-1.16.1-403.1.jar
|   Buzzier-Bees-1.16.1-2.1.0.jar
|   ceilingtorch-1.16.1-v1.8.jar
|   citadel-1.2.0.jar
|   collective-1.16.1-1.35.jar
|   curios-FORGE-1.16.1-3.0.jar
|   doubledoors_1.16-2.1.jar
|   DoubleSlabs-1.16-3.3.3.jar
|   dungeons-plus-1.16.1-1.0.2.jar
|   DungeonsMod-1.16.1-1.0.0.1.jar
|   elevatorid-1.16.1-1.7.3.jar
|   embellishcraft-1.16.1-3.0.0.0.jar
|   embellishcraft-bop-1.16.1-3.0.0.jar
|   Enhanced-Mushrooms-1.16.1-v2.0.8.jar
|   extlights-3.0.jar
|   Extra-Boats-1.16.1-1.4.1.jar
|   Flamingo-oh-oh-oh-1.0.1-MC1.16.1.jar
|   forbidden_arcanus-1.16.1-1.1.2.jar
|   Fusion-1.16.1-2.6.1.0.jar
|   guardvillagers-1.16.1-1.1.3.jar
|   ironchest-1.16.1-11.0.4.jar
|   livingthings-1.16.1-1.0.3.jar
|   Mantle-1.16.1-1.6.27.jar
|   mapperbase-1.16.1-2.0.0.0.jar
|   mcw-bridges-1.0.4-mc1.16.1.jar
|   mcw-doors-1.0.0-mc1.16.1.jar
|   mcw-trapdors-1.0.0fix-mc1.16.1.jar
|   mcws-roofs-1.16.1-v2.0.0.jar
|   mcws-win-1.16.1-v1.0.2.jar
|   MiddleMineRPG Ores and Equipments-1.0.0.jar
|   mining-helmet-1.16.1-1.0.8.jar
|   netheritehorsearmor-1.1.jar
|   NetherPortalFix_1.16.1-7.0.1.jar
|   NeverNeededOrWanted-1.16.1-1.0.4.jar
|   OnlySilver-1.16.1-3.1.0.2.jar
|   OptiFine_1.16.1_HD_U_G2.jar
|   PanzersMedievalWeapons-1.16.1-beta-V2.jar
|   Patchouli-1.16-39.jar
|   Quark-r2.2-264.jar
|   QuarkOddities-1.15.2.jar
|   ropebridge-1.16.1-2.0.jar
|   Savage-and-Ravage-1.16.1-2.1.1.jar
|   scuba-gear-1.16.1-1.0.1.jar
|   SimpleOres2-1.16.1-2.2.0.2.jar
|   SimpleTungsten-1.16.1-2.2.0.1.jar
|   structure-gel-api-1.16.1-1.2.1.jar
|   the-conjurer-1.16.1-1.0.8.jar
|   The-Endergetic-Expansion-1.16.1-2.0.0.jar
|   torchslabmod-1.16.1_v1.6.16.jar
|   Upgrade-Aquatic-1.16.1-2.0.1.jar
|   useful_backpacks-1.16.1-1.11.3.78.jar
|   u_team_core-1.16.1-3.1.4.182.jar
|   valhelsia_structures-16.0.2.jar
|   villagernames_1.16-2.4.jar
|   Waddles-1.16.1-0.8.7.jar
|   Waystones_1.16.1-7.1.1.jar
|   worleycaves-1.16.1-1.6.2.jar
|   XaerosWorldMap_1.10.1_Forge_1.16.1.jar
|   Xaeros_Minimap_20.20.1_Forge_1.16.1.jar

**Comment by glytch-g** [comment]
My current attempt with just inspirations has not reflected the error.

**Comment by KnightMiner** [comment]
Other than optifine which you said did not appear to cause it, I see nothing that stands out. So easiest way to test is to add back in half the mods at a time to try and find the cause. If the half you add in works, add in the other half instead. If the half you add in does not work, take out half of the mods until you find the offender. Should be able to figure out the cause in 3 to 4 iterations.

**Comment by glytch-g** [comment]
It is Optifine that is causing the issue.

**Comment by glytch-g** [comment]
And I see the closed post about it"Texture Tweaks Incompatible with Optifine 1.16 #177". Thank you

**Comment by glytch-g** [comment]
OptiForge-MC1.16.1-0.1.9 seemed to be a work around to use optifine and the mod.
