### ISSUE TITLE
disabling tweaks module crashes on startup.

### ISSUE THREAD

**Issue by tlitookilakin** [KnightMiner/Inspirations#183]
**Describe the bug**
Disabling tweaks module in config causes NPE on startup. To reproduce: in config/inspirationsModules.toml, change "InspirationsTweaks" to "false"

**Screenshots or crash report (if relevant)**
[Game log](https://gist.github.com/tlitookilakin/b5c32e9326a30f8fc6b9506ffa6d299f)

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Mantle: 1.5.15
 - Inspirations: 1.1.0
 - Forge: 31.2.43

**Other mods required**
None

**Comment by KnightMiner** [comment]
Modules are not supported in 1.15.2, the entire module loader was written for 1.12 and never got updated quite right. 1.16 fixes the issue, and I have mostly dropped 1.15 as I saw no reason not to update. So unfortunately, your best bet is to disable each option individually.

I should have a 1.16.3 released in the near future as well.

**Comment by tlitookilakin** [comment]
How do I disable each option individually? The only config files I have are InspirationsModules and Inspirations-replacements, and the second one only has options for a few features. I'd like to disable the crop tweaks and cauldrons only, but there is no option for those in either config file.

**Comment by KnightMiner** [comment]
The config file exists in the server config file, look into those a bit as I am not the only mod using them. Server configs are per world, meaning they sync much better for servers. There are default configs if you want to set them for all new worlds.

**Comment by tlitookilakin** [comment]
Oh, I didn't know you could set per-world configs, that's useful to know. thanks!
