### ISSUE TITLE
Firstperson shield block animation breaks when Inspirations is loaded with Rats

### ISSUE THREAD

**Issue by BugmanBugman** [KnightMiner/Inspirations#184]
**Describe the bug**
Title. Shield-blocking in first person is supposed to look like this
![image](https://user-images.githubusercontent.com/40730042/96391387-1cb35b80-117e-11eb-8e4d-47fac1984af4.png)
However, when those 2 mods are loaded together, it doesn't work.

**Screenshots or crash report (if relevant)**
https://streamable.com/uaw1j0

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Mantle: 1.6.40
 - Inspirations: 1.2.1.19

**Other mods required**
Rats
Citadel (dependency)

**Comment by KnightMiner** [comment]
This was a weird one. To explain what happened, I override the vanilla shield to make it enchantable. Normally this does not cause issues with the block animation as that is registered after I register my replacement, but Rats ignores Forge registration events causing vanilla to register its properties before my override.

I pushed a commit which fixes this by just registering the property for my override, so at least my code is less fragile. Will be in the next release

**Comment by KnightMiner** [comment]
Will be fixed in next release. Made a mistake in my fix in 1.2.1.23 (hard to catch as this does not happen in dev)

**Comment by KnightMiner** [comment]
Fixed in 1.2.1.24
