### ISSUE TITLE
enchantment level to maximum?

### ISSUE THREAD

**Issue by Mingu2209** [KnightMiner/Inspirations#185]
**Describe the bug**
I'm not sure if it's your mod, but I have a mod that increases the level of any enchantment to very high levels, like I can get fortune X or even more combining books. Is that possible that is your mod? I'm checking the config file:

Default power for a book for enchanting, can be overridden in the book overrides and it's 1.5 range. Is that possible? If so, with 0.0 should change to vanilla levels? Is the option in other part of the config file?

**Screenshots or crash report (if relevant)**
No screenshot available

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Mantle: Mantle-1.16.3-1.6.40
 - Inspirations: Inspirations-1.16.3-1.2.1.19

Sorry if it's not your mod. I wanted just to make sure that I undestood how it works and find the issue. Thanks in advance!

**Comment by KnightMiner** [comment]
No, its not my mod. That config you found was under the bookshelf section, implying its for bookshelves. An easier way to test this without making an issue would have been to remove my mod and see if it still happens for the record.
