### ISSUE TITLE
Carpeted Stairs Collision Problem

### ISSUE THREAD

**Issue by DrPoofington** [KnightMiner/Inspirations#189]
While walking or sprinting up carpeted stairs the player collides with the carpet block causing the player to start going prone as you would using a piston or trapdoor. It doesn't seem to cause the player to ever go fully prone but rather cause a "stuttering" effect. I tested it using only Inspirations and Mantle.

 - Minecraft: 1.16.3
 - Mantle: 1.16.4-1.16.43
 - Inspirations: 1.2.1.24

**Comment by KnightMiner** [comment]
Fixed in 1.2.2
