### ISSUE TITLE
Crash upon checking recipes when extendCauldron=simple

### ISSUE THREAD

**Issue by Tetrajak** [KnightMiner/Inspirations#19]
Minecraft Version: 1.12.2
Forge Build: 2590
Mod Version: 0.1.1b
JEI Version: crash happens on both 4.8.5.143 & .146

To reproduce, set extendCauldron to simple in the config, launch the game, create a new world or load an existing one, search cauldron in JEI, hover over the cauldron and press "u" for uses, then click the cauldron title in the GUI (which appears empty, btw).

**Comment by KnightMiner** [comment]
Crash report? Paste it on pastebin then link it here.

**Comment by Tetrajak** [comment]
Ah sorry, the one thing I forgot; https://pastebin.com/53zbcSFV

**Comment by KnightMiner** [comment]
Hmm, I found the issue, though it shouldn't be causing a crash, just no recipes to show.

**Comment by KnightMiner** [comment]
Fixed in 0.1.2
