### ISSUE TITLE
Sugar cane needs a fix

### ISSUE THREAD

**Issue by DrWhite01** [KnightMiner/Inspirations#191]
Before anything I want to clarify that I'm still learning english so I am sorry if I misspell some words

**Describe the bug**
When I look at the growning bit of the sugar cane it says "cactus seeds", and if I try to bone meal it, it just keep consuming the bone meal without growing

**Screenshots or crash report**

It wont let me upload an image so here is a discord link:

https://cdn.discordapp.com/attachments/751927865213452302/782089162664312872/2020-11-28_00.35.42.png 
(It's a screenshot, not a server link)

**Versions**
 - Minecraft: 1.16.1
 - Mantle: 1.16.1-1.6.27
 - Inspirations: 1.16.1-1.2-0

**Other mods required**

Hwyla 1.10.10-B77_1.16.1 (The last version I think)

-----------------------------------------------------

IDEA: (Please read)
Also something I think is worth mentioning is that the grow speed of the sugar cane is really slow, too slow. So I think I know how to fix it. Acording to the minecraft wiki, one sugar cane grows when the top block of the sugar cane has recived 16 random ticks, so my idea is that every time the top sugar cane recives one tick (the normal vanilla sugar cane) the growing sugar cane grows 1 pixel, making it so that it transforms into a fully grown sugar cane every 16 ticks (like a normal sugar cane).

**Comment by KnightMiner** [comment]
Two of your issues are fixed by updating to 1.16.2+, I no longer support 1.16.1 because its a trivial update to the latest 1.16.

I'll leave this open as a reminder to look into the bonemeal bug.

**Comment by KnightMiner** [comment]
Fixed in 1.2.2
