### ISSUE TITLE
Bug/Crash tooltip with Enchanted Shield with Banner

### ISSUE THREAD

**Issue by bootstrapbill22** [KnightMiner/Inspirations#192]
One of my players enchanted a shield that had an ominous banner pattern applied to it, and at that point kept crashing out of the game. We don't know what the enchant was as mousing over the shield causes the crash.
He was able to drop the shield into a hopper, at which point he remained in game, and when the shield is moused over in the hopper the client of whoever does so crashes.

I'm assuming this is Inspiration caused as this is the only mod referenced in the crash and the reference is to fixShieldTooltip.
Pastebin of crash log: https://pastebin.com/H42iWMsw

We can just avoid enchanting patterned shields so no big issue for us. I just hope the log is helpful.
Have a good day.

**Comment by KnightMiner** [comment]
Disable the client config option for fixShieldTooltip. If I remember, it's just a whitespace fix. I'll look into properly fixing this when I have more time.

**Comment by HonestAngel** [comment]
I had the same problem, but it was because I opened a chest with an shield from your mod.... Crashed twice...

[crash-2020-12-12_19.11.12-client.txt](https://github.com/KnightMiner/Inspirations/files/5684147/crash-2020-12-12_19.11.12-client.txt)

**Comment by KnightMiner** [comment]
Fixed in 1.2.2
