### ISSUE TITLE
How to change individual parts of modules?

### ISSUE THREAD

**Issue by grandogarndo** [KnightMiner/Inspirations#193]
Not really a bug report, but when I try to modify one of the specific parts of a module (in my case the sugarcane/cactus seeds) I just can't find the config. The only ones that pop up are "modules" and "replacements" and this mod is so great I don't want to disable all of tweaks for one little thing.

**Comment by KnightMiner** [comment]
Server config, it's in the world folder.

**Comment by grandogarndo** [comment]
Thanks!
