### ISSUE TITLE
Incompatibility with Performant

### ISSUE THREAD

**Issue by BugmanBugman** [KnightMiner/Inspirations#194]
**Describe the bug**
Cauldron severely glitch out when putting milk in it, with the Rats mod

**Screenshots or crash report (if relevant)**
![2020-12-26_13 49 45](https://user-images.githubusercontent.com/40730042/103158454-a0dc1d80-4783-11eb-9dcf-c64f1e4bcbe8.png)

https://user-images.githubusercontent.com/40730042/103158459-aa658580-4783-11eb-8ced-bbfa74e0e7b1.mp4

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Mantle: 1.6.43
 - Inspirations: 1.2.1.24 for 1.16.x

**Other mods required**

Rats

**Comment by KnightMiner** [comment]
Get me a minimal list of mods to reproduce this, as in reproduce with no other mods if possible. It works fine with just Rats and Inspirations in my testing, and you have quite a few mods evident in that screenshot besides the two. 

I'm not sure what your video is trying to show as it really does not like playing properly, apart from the fact that green particles are the normal way Inspirations shows cauldron contents are changing. There is a recipe that turns milk into cheese if you wait a bit. A video longer than 5 seconds would also have helped quite a bit to show your point.

**Comment by BugmanBugman** [comment]
I apologize for the video, but  i can determine that the cause of the issue is not in fact rats but Performant. I'm aware that it's closed source, so would you prefer me close this issue and report it to them?
Here's another video

https://streamable.com/9e8n7x

Explanation: the row of buckets is caused by right clicking the cauldron of milk.

**Comment by KnightMiner** [comment]
Report the issue to them, but leave this one open and cross link it. That way me and the performant author can try to work out a solution.

This could still be on my side even as a performant conflict, so I'd rather leave this open until we can determine the problem.

**Comment by BugmanBugman** [comment]
https://github.com/someaddons/performant_issues/issues/62

**Comment by KnightMiner** [comment]
Fixed on performant's side
