### ISSUE TITLE
Gray ink bottle missing name

### ISSUE THREAD

**Issue by ghost** [KnightMiner/Inspirations#195]
**Describe the bug**
The gray ink bottle item is missing its tooltip name.
![2021-01-01_15 53 00](https://user-images.githubusercontent.com/8272619/103446143-63c3cf80-4c4a-11eb-9d3a-c0c317e46a46.png)
**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Mantle:  1.6.43
 - Inspirations: 1.2.1.24

**Other mods required**
Tested with only Mantle and Inspirations, still present

**Comment by KnightMiner** [comment]
Somehow a dumb `.` got in the name so I'm localizing `item.inspirations.gray_dyed_bottle.`

**Comment by ghost** [comment]
good on ye lad

**Comment by KnightMiner** [comment]
Fixed in 1.2.2
