### ISSUE TITLE
Item Shelf Block Name & Item Information in HYWLA/Jade

### ISSUE THREAD

**Issue by slainless** [KnightMiner/Inspirations#197]
**Is your feature request related to a problem? Please describe.**
Item shelf's block name is "itemshalf" in HYWLA/Jade, and sometimes, we need to see a detailed information about the item placed on the shelf.

**Describe the idea**
Fix the block's name and add integration to HYWLA/Jade to display information about the item currently displayed on the shelf.

**Describe how you think this feature would fit in vanilla**
This will not impact vanilla gameplay, but this will surely integrate inspirations better with modded environment

**Comment by slainless** [comment]
Wrong mod, lol

**Comment by KnightMiner** [comment]
Wrong mod? Does this issue not affect Inspirations?

**Comment by slainless** [comment]
No. Sorry, I mistook supplementaries' item shelf as inspiration's.
