### ISSUE TITLE
Disabling certain features in the config doesn't remove them from the recipe book.

### ISSUE THREAD

**Issue by enduum** [KnightMiner/Inspirations#198]
**Describe the bug**
Disabling certain features in the server config does not remove those features from the recipe book, prevent the recipes being unlocked, or stop the recipes from working. Have tried disabling whole modules (tools and building), disabling individual items (photometer, barometer, glass doors, anything), and disabling whole modules plus the individual items with no success.
Edit: To be clear, it's only recipes that don't seem to respond to the config, other features such as cauldron changes and rope ladders can be enabled and disabled with no issue.

**Expected behaviour**
Disabling a feature in the config disables it in the game.

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Mantle: 1.6.74
 - Inspirations: 1.2.2

**Other mods required**
Tested on a clean install with no other mods.

**Comment by KnightMiner** [comment]
Did some testing, looks like the load order changed in a recent update, either 1.15 or more likely 1.16. Now recipes load before the Forge config loads, as a result the config is checked too late. As another side effect of this issue, opening a different world may cause the config from the previous world to be used for recipes.

I will have to think about how to fix this, will not be easy, so for now this not getting addressed any time soon.

**Comment by KnightMiner** [comment]
Fixed in 1.18 by migrating a lot of these options to a common config. Unable to fix this for 1.16 without breaking old modpack configs.
