### ISSUE TITLE
Ice and Fire: Dragons Bestiary book incompatible with Inspirations Bookshelf

### ISSUE THREAD

**Issue by LighttronPrime** [KnightMiner/Inspirations#199]
The Bestiary book from Ice and Fire can not be placed in the Inspirations Bookshelf. 

 - Minecraft: 1.16.4
 - Mantle: 1.6.79
 - Inspirations: 1.2.2
 - Ice and Fire: 2.1.5
 - Citadel: 1.5.3

**Comment by KnightMiner** [comment]
Thats why I have a config, with a list of keywords that make something a book. Have a tag too, they can tag their book and it will work on my shelves, or you can do so yourself in a datapack.
