### ISSUE TITLE
Broken bookshelf become oak

### ISSUE THREAD

**Issue by DcNdrew** [KnightMiner/Inspirations#2]
I broke a dark oak bookshelf with an axe and it became simple oak bookshelf.

**Comment by KnightMiner** [comment]
This will be fixed in the next version. Apparently I was caching the texture using the same NBT tag as the texture stack, so it was deleting the stored stack. Unfortunately, this means any bookshelves you placed previously may revert to oak, but anything after this update will be fine.

**Comment by KnightMiner** [comment]
Fixed in Inspirations 0.1.1, now on CurseForge
