### ISSUE TITLE
1.16.4 Villager won't assign to Cauldron

### ISSUE THREAD

**Issue by GreyOfHearts** [KnightMiner/Inspirations#200]
**Describe the bug**
For Inspirations 1.2.1.24 version 1.16.x, Villagers won't assign to the Cauldron to become Leatherworkers. While most Villagers walk to the job block and pick their role, they just wander around the Cauldron and act as if it isn't there. I'm using the latest version of Forge 1.16.4, and this is the only mod I have that touches the Villagers or the Cauldron (except maybe Mantle, but that's it). All other Villager roles work perfectly and Leatherworker didn't stop working until Inspirations was installed.

If this is an easy fix or I missed the solution in another bug report/wiki article, then my apologies! Any and all help is appreciated! Great work on this mod btw, I couldn't live without it.

**Versions :**
 - Minecraft: 1.16.4
 - Mantle: 1.6.52
 - Inspirations: 1.2.1.24
 - Architectury: 1.5.105

**Other Installed Mods (All up to date):**
- Lucky Block
- Absent by Design
- Netherite Plus
- SimpleOres
- SimpleCoreLib
- SMATM
- Structurize
- WorldEdit
- Xaeros Minimap

**Comment by KnightMiner** [comment]
The last question is not other installed mods, its other required mods. As in, which other mods are required for this issue? Test with just Inspirations if possible.

Reason I ask is I already fixed this issue back in 1.15. And I am pretty certain my fix ported over properly.

**Comment by GreyOfHearts** [comment]
So sorry, I just tested each mod one by one and it seems to work perfectly in Single Player. For some reason, it's bugged on my server so I'll have to find a way to fix that. Sorry for the confusion!

**Comment by KnightMiner** [comment]
Any way you can test just Inspirations on a server? If I am breaking things would be nice to know (though no idea why my fix would only work in SP)

**Comment by GreyOfHearts** [comment]
I didn't test Inspirations on its own yet, but I did disable the new Cauldron functions in the config files and Villagers started using it as a job block again. This causes the Cauldron texture to be missing, though. I use Multicraft to host my server, and digging around I couldn't find any settings or configs that conflict with yours so idk what happened there.

Edit: The server with just Inspirations and Mantle doesn't let the Villager use the Cauldron, yet in Singleplayer it still does.

**Comment by KnightMiner** [comment]
What server software are you using? Forge? If not Forge, test with a Forge server.

**Comment by MoonMoonShark** [comment]
i have not tested it by itself, but i can confirm that on my server as well, villagers were refusing to use the cauldron to take a job.

Versions:

Minecraft: 1.16.5
Forge 36.1.16
Mantle: 1.6.97
Inspirations: 1.2.2
Architectury: 1.14.157

Modpack: https://www.curseforge.com/minecraft/modpacks/the-lighthouse

**Comment by KnightMiner** [comment]
Test it by itself then. I don't know whether this is a mod conflict or it's actually broken if you test in a pack.

**Comment by GreyOfHearts** [comment]
Sorry for being away so long, but yes I was using a Forge server with the correct version. Still no idea why it works just fine on singleplayer, might just find a new hosting site or something.

**Comment by KnightMiner** [comment]
6a11407 will probably fix this issue, in the next mod build. Not sure exactly what is causing it, but I managed to find a modpack that has the issue and test with that fix.
