### ISSUE TITLE
after disabling fitted carpet feature, world wont load

### ISSUE THREAD

**Issue by agr21** [KnightMiner/Inspirations#203]
**Describe the bug**
I had both inspirations and carpet stairs mod(not sure if relevant), and i wanted to disable inspirations' carpet stairs module after it didnt have a desired modded carpet, and after changing the config line, the world wouldnt load. there werent any carpets placed down on stairs. 
**Screenshots or crash report (if relevant)**
https://paste.ubuntu.com/p/RgyCNxrJDT/
the datapack errors are not important, they work fine,issue is same without them

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Mantle: 1.16.5.-1.6.79
 - Inspirations: 1.16.5.- 1.2.2

**Comment by KnightMiner** [comment]
Hmm, looks like a tag loading issue. Mod should be unconditionally registering fitted carpets and just disable them if the feature is disabled, as only the vanilla block substitution is the problematic code there. Should be an easy fix whenever I find time to work on Inspirations again (been distracted with real life and a few of my other mods)

As a temporary fix, you might be able to make a datapack with the `minecraft:carpets` tag, and set `"replace": true`. Then just make sure it includes relevant carpets.

**Comment by agr21** [comment]
thanks, i will look into how to do that :) and take your time, love the mod!

**Comment by KnightMiner** [comment]
Fixed in 1.2.3
