### ISSUE TITLE
cauldron mod support

### ISSUE THREAD

**Issue by 0Navis0** [KnightMiner/Inspirations#204]
- Tough As Nails
    - toughasnails:dirty_water_bottle
    - toughasnails:purified_water_bottle
    - toughasnails:water_canteen
    - toughasnails:dirty_water_canteen
    - toughasnails:purified_water_canteen
- Atmospheric
    - atmospheric:yucca_juice
    - atmospheric:aloe_gel_bottle
- Autumnity
    - autumnity:syrup_bottle
    - autumnity:foul_soup
- Upgrade Aquatic
    - upgrade_aquatic:mulberry_jam_bottle
- Neapolitan
    - neapolitan:milk_bottle
    - neapolitan:chocolate_milkshake
    - neapolitan:strawberry_milkshake
    - neapolitan:vanilla_milkshake
    - neapolitan:banana_milkshake
    - neapolitan:mint_milkshake
    - neapolitan:adzuki_milkshake
    - neapolitan:strawberry_banana_smoothie
    - neapolitan:adzuki_stew
- Peculiars
    - peculiars:yucca_milkshake
    - peculiars:aloe_milkshake
    - peculiars:passionfruit_milkshake
    - peculiars:aloe_berry_smoothie
- Farmers Delight
    - farmersdelight:milk_bottle
    - farmersdelight:hot_cocoa
    - farmersdelight:tomato_sauce
    - farmersdelight:beef_stew
    - farmersdelight:chicken_soup
    - farmersdelight:vegetable_soup
    - farmersdelight:fish_stew
    - farmersdelight:pumpkin_soup
    - farmersdelight:baked_cod_stew
    - farmersdelight:noodle_soup
- Abnormals Delight
    - abnormals_delight:cherry_cream_soda
    - abnormals_delight:passion_aloe_nectar
    - abnormals_delight:pickerelweed_juice
- Abundance
    - abundance:lavender_tea
- Bayou Blues
    - bayou_blues:gooseberry_juice
    - bayou_blues:gooseberry_jam
- Enhanced Mushrooms
    - enhanced_mushrooms:beef_stew
- Simpy Tea
    - simplytea:cup_tea_black
    - simplytea:cup_tea_green
    - simplytea:cup_tea_floral
    - simplytea:cup_tea_chai
    - simplytea:cup_tea_chorus
    - simplytea:cup_tea_iced
    - simplytea:cup_cocoa
- Botania
    - botania:brew_vial
    - botania:brew_flask
- Create
    - create:builders_tea
    - create:honey_bucket
    - create:chocolate_bucket
- Thermal Series
    - thermal:xp_stew

**Comment by KnightMiner** [comment]
Potion support is automatic. If its not working, those mods are doing something wrong.

Regarding the remaining list, I will echo what I said on your other issue. If you want to make a list of IDs relevant to the feature (item IDs, fluid IDs, etc), I can look into it. A laundry list of features to add is not the most helpful. Also remember you can add a datapack.

**Comment by 0Navis0** [comment]
Yeah it seems Enigmatic Legacy does something wrong with its potion, it's not recognized neither by fluid encapsulator from Thermal and spout from Create.

**Comment by 0Navis0** [comment]
I updated the list with all the item ids like you asked. I hope it can help you.

**Comment by Hypsellis** [comment]
I updated again the list, added the drinks from abnormals delight, and corrected few wrong names.

**Comment by KnightMiner** [comment]
I do not plan to further develop the cauldron on 1.16. With how cauldrons work in 1.18, its on the other mods to add support by adding cauldrons for their stuff if they wish.

Note that Inspirations lets you add custom cauldron contents in 1.16 so you could have defined all this stuff yourself via datapack + resource pack.
