### ISSUE TITLE
Activared Redstone Torch Lever looks weird with certain resource packs

### ISSUE THREAD

**Issue by darthvader45** [KnightMiner/Inspirations#205]
**Describe the bug**
A clear and concise description of what the bug is, including expected behavior.

**Screenshots or crash report (if relevant)**

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Mantle: 1.3.3.55
 - Inspirations 

**Other mods required**

List any other mods required to reproduce this issue. Test by running the game with minimal mods.

**Comment by KnightMiner** [comment]
You filled out none of the issue template. Plus this is a resource pack problem. Plus this feature was removed in 1.16 and I doubt 1.12 is getting another build.
