### ISSUE TITLE
composter crash

### ISSUE THREAD

**Issue by Nia-laa** [KnightMiner/Inspirations#206]
**Describe the bug**
Unexpected and unrepeatable crash error occurred involving the composter

 - Minecraft: 1.16.5
 - Mantle: 1.6.79
 - Inspirations: 1.2.2

**Other mods required**
69 mods loaded when crash occured

[crash-2021-03-08_13.24.39-fml.txt](https://github.com/KnightMiner/Inspirations/files/6103576/crash-2021-03-08_13.24.39-fml.txt)

**Comment by KnightMiner** [comment]
Fixed in 1.2.3 by 152b7df
