### ISSUE TITLE
Shaders crash while rendering cauldron

### ISSUE THREAD

**Issue by BugmanBugman** [KnightMiner/Inspirations#207]
**Describe the bug**
Crash out of no where, presumably due to optifine

**Screenshots or crash report (if relevant)**
https://gist.github.com/BugmanBugman/ff9a1bc17b723d2f4225e98222b860dd

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Mantle: 1.6.79
 - Inspirations: 1.2.2

**Other mods required**
Optifine

List any other mods required to reproduce this issue. Test by running the game with minimal mods.

**Comment by KnightMiner** [comment]
That is not a full crash report, you missed half the report. Please add a full crash report.

Please also test without Optifine, does the issue still happen?

**Comment by KnightMiner** [comment]
Closing for lack of response, I cannot do anything with half a crash report.
