### ISSUE TITLE
Locks don't stop Chest from being broken in my modpack.

### ISSUE THREAD

**Issue by Camawama** [KnightMiner/Inspirations#208]
I wish they had a spoiler option on this but here is a list of active mods. I don't see how any of these could be a problem that stops locks from functioning properly...unless it is already possible. I was in creative, put a lock on a chest, and had my friend try and break it (in survival). He couldn't open the chest, but he could break it...that, in my eyes is a problem.

**Comment by Camawama** [comment]
Waddles (by Girafi)
XP Tome (by bl4ckscor3)
Create (by simibubi)
Polymorph (Forge) (by TheIllusiveC4)
Customizable Elytra (by Hidoni)
Structure Gel API (by ModdingLegacy)
SecretRoomsMod (by AbrarSyed)
Easy Magic (by Fuzs_)
AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)
Vanilla Hammers [Forge] (by MelanX)
Damage Tilt (by Charles445)
Server Utilities (by ArrowsendGaming)
Enhanced Celestials - Blood Moons & Harvest Moons (by Corgi_Taco)
Outvoted (by HowBoutNo)
Wandering Trapper (by lilypuree)
Wall-Jump! [FORGE] (by genandnic)
Abnormals Core (by TeamAbnormals)
Cat Has Wares (by Rorazoro)
Repurposed Structures (Forge) (by telepathicgrunt)
Waystones (by BlayTheNinth)
Ding (by ohaiiChun)
OptiForge (by ZekerZhayard)
Simple Planes (Forge) (by przemykomo)
Explosion't (by Harmonised_)
Dungeons Plus (by ModdingLegacy)
GraveStone Mod (by henkelmax)
Bookshelf (by DarkhaxDev)
Structure Expansion (by Sunekaer)
OpenBlocks Elevator (by vsngarcia)
MoreVanillaLib (by MelanX)
Savage & Ravage (by TeamAbnormals)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Unique Enchantments (by Speiger)
Lost Trinkets (by owmii)
Crumbs (Forge) (by Trikzon)
Camera Mod (by henkelmax)
Botany Pots (by DarkhaxDev)
Redstone Gates (by se7kn8)
Dungeon Crawl (by XIROC1337)
CraftTweaker (by Jaredlll08)
Champions (by TheIllusiveC4)
When Dungeons Arise (by Aureljz)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
U Team Core (by HyCraftHD)
VanillaTweaks (by StrikerRocker)
Quark (by Vazkii)
AutoRegLib (by Vazkii)
Randomite Classic (by ModdingLegacy)
Mantle (by mDiyo)
Xaero's World Map (by xaero96)
Useful Backpacks (by HyCraftHD)
Better Burning (by DarkhaxDev)
Biomes O' Plenty (by Forstride)
Creeper Confetti (by SR2610)
Forgiving Void (by BlayTheNinth)
Better Title Screen (by Girafi)
FallingTree (by RakSrinaNa)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Console Experience (by Fuzs_)
Enchantment Descriptions (by DarkhaxDev)
SwingThroughGrass (by exidex)
AttributeFix (by DarkhaxDev)
End Remastered (by jack_bagel)
[Forge] Expanded Storage (by NinjaPhenix)
AppleSkin (by squeek502)
[FORGE] Iron Furnaces (by XenoMustache)
Just Enough Items (JEI) (by mezz)
Progressive Bosses (by Insane96MCP)
Lollipop (by owmii)
Overloaded Armor Bar (by tfarecnim)
ReAuth (by TechnicianLP)
Patchouli (by Vazkii)
Charm Reforged (by svenhjol)
RandomPatches (Forge) (by TheRandomLabs)
Ores Above Diamonds (by Squidsword)
Aquaculture 2 (by Shadowclaimer)
BetterDefaultBiomes (by Xratedjunior)
GoProne (by Alpvax)
Alex's Mobs (by alex1the1666)
Extra Golems (by skyjay1)
Spartan Shields (by ObliviousSpartan)
World Pre Generator (by GeheimagentNr1)
Mouse Tweaks (by YaLTeR)
Upgrade Aquatic (by TeamAbnormals)
Inspirations (by KnightMiner)
Dynamic Surroundings (by OreCruncher)
GeckoLib (by ThanosGecko)
Enchanted Book Redesign (by tfarecnim)
Vanilla Excavators [Forge] (by MelanX)
Citadel (by alex1the1666)
Coins JE (by DarkhaxDev)
JEITweaker (by Jaredlll08)
BetterEnd (Forge) (by Beethoven92)
Spiders 2.0 (by TheCyberBrick)
Dungeons Mobs (by the_infamous_1)

**Comment by KnightMiner** [comment]
Locks simply expose a vanilla mechanic in survival, they are simply a deterrent, like locks in real life. The point is not your friend cannot rob you, the point is you know if your friend robs you.

Additionally, letting people craft an unbreakable block is just too easy to abuse by griefers. Imagine your base surrounded by chests you cannot break. So no, I have no plans to make them unbreakable. If you have an idea to solve this problem without making it unbreakable I would be interested in hearing it.
