### ISSUE TITLE
Pipes Through Walls

### ISSUE THREAD

**Issue by Camawama** [KnightMiner/Inspirations#209]
**Is your feature request related to a problem? Please describe.**
I don't believe it's a problem

**Describe the idea**
Pipes should be able to travel through walls

**Describe how you think this feature would fit in vanilla**
Pipes going through walls could be a very clean way of making cool contraptions
![image](https://user-images.githubusercontent.com/43620900/112744426-9f2e1b80-8f65-11eb-81d2-c95226a78654.png)

**Comment by KnightMiner** [comment]
Inspirations is a vanilla++ mod, meaning I add features I believe would fit in vanilla. Pipes going through walls is not something I believe fits in vanilla as vanilla has never been about giving you super compact structure. If you dislike how small it is inside the blocks, use a full size hopper in the wall and switch back to pipes after.
