### ISSUE TITLE
Villagers Refuse to Leave Home Through Glass Door Exits

### ISSUE THREAD

**Issue by Darkosto** [KnightMiner/Inspirations#210]
**Describe the bug**

Hello!

I am a moderately famous, award winning designer for car insurance renewal forms. It is my duty to provide customer service representatives the documents they need to fulfil(l) their employment obligations. Many families rely on my knowledge, intuition, wisdom, skills, experience, and expertise. I take that responsibility very seriously.

Just like I take villagers not opening your glass doors **_very_** seriously. I expect to build a luxurious temple to the gods using glass doorways. None of that oak wood, splintered nonsense! Oak doesn't even stop airflow because there's a gigantic hole in right in the middle! How dare they!

**Screenshots or crash report (if relevant)**
![image](https://user-images.githubusercontent.com/10309699/113366063-0143a380-930d-11eb-85cb-dd57f91651d0.png)

See image 1: villagers stuck inside their abode because they are unable to open the door. They are also discussing amongst themselves evil plans and it's your fault. What if they blow my base up?

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Mantle: 1.6.79
 - Inspirations: 1.2.2

I have like 90 of them. They are _required_ but they are not required.

List any other mods required to reproduce this issue. Test by running the game with minimal mods.
You need Forge. I think you might need Minecraft too. Not Minecraft 2, since that's not out yet. Between us, I think Minecraft 2 will put Minecraft 1 to shame.

**Comment by DetroitWhiskey136** [comment]
I can confirm this issue

**Comment by KnightMiner** [comment]
MinecraftForge/MinecraftForge#7767 will give me a method to fix this, so for now this is on hold for Forge

**Comment by KnightMiner** [comment]
Fixed in 9b04f81, which is in release 1.2.3.37
