### ISSUE TITLE
Ink bottle lose type when placed back into cauldron

### ISSUE THREAD

**Issue by KajesLorian** [KnightMiner/Inspirations#211]
Once you use a bottle to pull the ink out of a cauldron, if you happen to re-place the ink back in the cauldron and take it back out again, it looses whatever color it was, and just becomes "Ink Bottle".

![image](https://user-images.githubusercontent.com/16963626/113780480-439a2580-96fd-11eb-88cc-31e94bbbec7d.png)

![image](https://user-images.githubusercontent.com/16963626/113780883-d33fd400-96fd-11eb-8676-6c1492abe5ae.png)

 - Minecraft: 1.16.4 
 - Forge: 35.1.36
 - Mantle: 1.16.5-1.6.79
 - Inspirations: 1.16.5-1.2.2

**Comment by KnightMiner** [comment]
Please give a bit more information. Did the cauldron contain anything else? There is logic for mixing ink bottles in Inspirations, so if you had another color in there it would mix, or if you had normal water

Also, have you tried with other colors, or just light grey?

**Comment by KajesLorian** [comment]
Nothing else was in the cauldron. I was mass-dying white-stained glass, so I was making up multiple white dye bottles. I placed a Bucket of water in, and was rapidly filling empty bottles. Going too fast I would accidentally re-pour the last bottle back into the empty cauldron.

After testing it does have the same effect on all dyes. All single bottles are generic Ink bottles, and below them the dye bottles they used to be, and below them the dye used. I can make up a gif of it tomorrow if you'd like to see it in action.

![image](https://user-images.githubusercontent.com/16963626/113813609-36515b00-973e-11eb-9438-ba2c05e41cab.png)

![image](https://user-images.githubusercontent.com/16963626/113813646-49fcc180-973e-11eb-8a29-c2f5b408b252.png)

**Comment by KnightMiner** [comment]
Fixed in 1.2.3
