### ISSUE TITLE
Port Smooth Growth to config

### ISSUE THREAD

**Issue by darthvader45** [KnightMiner/Inspirations#212]
**Is your feature request related to a problem? Please describe.**
Cactus and sugarcane grow in stages right now, and it's impossible to turn off, making current auto farms much slower than intended.

**Describe the idea**
I noticed that the smooth growth thing in this mod for sugarcane/cactus was a config option back in 1.12.2.  Just wondering if this can be ported to 1.16.5.  I understand if this is not possible, and if so, you can close this immediately.

**Comment by KnightMiner** [comment]
Server config. Its in the world folder. Read about default configs if you make a modpack.
