### ISSUE TITLE
Composter crash with tweaks module

### ISSUE THREAD

**Issue by cdcp998** [KnightMiner/Inspirations#213]
server 
https://paste.ubuntu.com/p/qdXj6bVVvC/

**Comment by KnightMiner** [comment]
This is not a java 16 crash, this is a race condition. Looks to be the same as #210, but I missed a case. You may find the crash does not happen the next time you run the game.

**Comment by cdcp998** [comment]
But I use java11 to work. Using java16 will crash

**Comment by KnightMiner** [comment]
Its a race condition. Race conditions are caused by many different things. Changing java version could cause it, or changing mod list, or loading up the game during a full moon.

**Comment by KnightMiner** [comment]
Fixed in 1.2.3.37
