### ISSUE TITLE
cauldron recipes does not work in latest forge version

### ISSUE THREAD

**Issue by k1r0s** [KnightMiner/Inspirations#215]
**Describe the bug**
A clear and concise description of what the bug is, including expected behavior.

- steps
place a cauldron above a magma block, fill it with water, then, after the water boils, drop 4 mushrooms.
- expected result
mushroom soup is crafted
- actual result
mushrooms are not processed

**Screenshots or crash report (if relevant)**

**Versions (please complete the following information):**
 - Minecraft: 1.16.1 > 1.16.5**
 - FORGE: 36.1.32
 - Mantle: Mantle-1.16.5-1.6.109
 - Inspirations: Inspirations-1.16.5-1.2.3.37

**Comment by KnightMiner** [comment]
Does it work if you right click the cauldron with the mushrooms? Dropping was never the main way to craft.

**Comment by k1r0s** [comment]
So water only "boils" when fire is placed under the cauldron. Other heat sources doesn't make it boil. I don't know if this is an expected feature but in 1.12.2 it was

**Comment by k1r0s** [comment]
Just to clarify. Doing right click with the recipe items rather than throwing them directly into the cauldron only works when water actually boils. That only happens when fire is below the cauldron.

**Comment by KnightMiner** [comment]
Magma blocks never made it boil in Inspirations, that was an addon/modpack. Sounds to me like you assumed it was boiling when it was not. If you saw bubble particles, this is a bug, but otherwise this is misunderstanding mechanics.

Currently supported sources of boiling are fire and campfires.

**Comment by k1r0s** [comment]
thanks for the info.

To anybody running into this conversation in the future:

I'd mistake dynamic surrounding particles which make cauldron interact with other "heat sources" but actually it was not inspirations::boiling_water :'))
