### ISSUE TITLE
Add Cauldron Fire Configurability

### ISSUE THREAD

**Issue by oremilk** [KnightMiner/Inspirations#218]
**Is your feature request related to a problem? Please describe.**
Right now, it seems only fire and the campfire count as a heating source for Cauldron Potions, but there are many other blocks that could count as well such as magma blocks. Also, other mods add similar blocks that fit into the heating element aesthetic.

**Describe the idea**
Adding an option to configure what types of blocks are considered "heat sources" for the Cauldron Potions mechanic.

**Describe how you think this feature would fit in vanilla**
This feature is more for modpacks and integration with other mods.

**Comment by TeamSpen210** [comment]
This is already configurable using a datapack, simply add the relevant blocks to the [`inspirations:cauldron_fire`](https://github.com/KnightMiner/Inspirations/blob/1.16/src/generated/resources/data/inspirations/tags/blocks/cauldron_fire.json) or [`inspirations:cauldron_ice`](https://github.com/KnightMiner/Inspirations/blob/1.16/src/generated/resources/data/inspirations/tags/blocks/cauldron_ice.json) tags.

**Comment by KnightMiner** [comment]
Magma blocks intentionally do not count as they are too trivial. I wanted a bit of challenge to heat the cauldron by making the heating source actually burn you and surroundings. Campfires broke that, but they just looked so good it had to be allowed.

But yes, like TeamSpen said, tags are your friend.
