### ISSUE TITLE
Config Error: Mismatched options

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#22]
This snippet is from the cfg.
 cauldron {
        # Allows cauldrons to be filled with dyes and dye items using cauldrons [default: true]
        B:brewing=true
        # Allows cauldrons to be filled with potions and support brewing [default: true]
        B:dyeing=true

Dyeing and brewing are under each-others comment.

**Comment by KnightMiner** [comment]
Already fixed by 12a74a0

**Comment by KnightMiner** [comment]
Fixed in 0.1.2
