### ISSUE TITLE
{MOD CONFLICT} CRASH when brewing potions in a cauldron with Inspirations, Supplementaries & survival essentials installed

### ISSUE THREAD

**Issue by Cynix32** [KnightMiner/Inspirations#222]
**Describe the bug**
Inspirations mod adds a way of crafting potions using a cauldron. Brewing potions that way causes a crash when survival essentials mod is also installed
Referencing omegaleo/mc-survessentials-mod#14

**Versions (please complete the following information):**
windows 10
forge 36.2.8
java 8
mc 1.16.5
Inspirations-1.16.5-1.2.3.38.jar
Mantle-1.16.5-1.6.127.jar

**Other mods required**
selene-1.16.5-1.8.1.jar
supplementaries-1.16.5-0.17.6.jar
survivalessentials-1.16.4-1.5.0.jar
List any other mods required to reproduce this issue. Test by running the game with minimal mods.
I have done meticulous testing of my modpack with almost 500 mods, and have done confirmatory testing to narrow it down to just all these mods installed.

**Comment by KnightMiner** [comment]
Telling me something crashes without providing a crash report is useless. Give me a crash report or I cannot help you.

**Comment by Cynix32** [comment]
oh right I forgot, i thought I pasted the pastebin link so here it is:
https://pastebin.com/hRdPPP1Z

**Comment by KnightMiner** [comment]
Looks like someone is returning a null itemstack as a result from the brewing itemstack getter. Null itemstacks have been illegal since 1.11, so someone is doing something dumb. Not certain who as the stacktrace does not tell me which recipe is to blame

Edit: looked in their source code for about 5 seconds, its mc survival essentials

**Comment by KnightMiner** [comment]
Closing as fixed in the other mod.
