### ISSUE TITLE
Cauldrons have weird texture on them

### ISSUE THREAD

**Issue by p1ut0nium-git** [KnightMiner/Inspirations#224]
**Describe the bug**
With Inspirations Cauldrons enabled, there is a strange flower-like texture on it. Any way to fix this? Also, it seems that a heated cauldron full of water has the correct texture. It has burning netherrack under it.

Also, disabling Inspiration Cauldrons, causes the cauldrons to now have a missing texture.

Config for missing textures (after having it enabled):
#Replace the cauldron block to allow it to hold other liquids and perform extended recipes.
cauldron = false

**Screenshots or crash report (if relevant)**
![2021-11-12_13 20 58](https://user-images.githubusercontent.com/60378380/141523092-e7be3035-86cb-41f3-9df6-d956231e6286.png)

Heated Cauldron
![2021-11-12_13 30 38](https://user-images.githubusercontent.com/60378380/141524232-684a25c6-d2ca-479d-b2ad-580e8cac20bf.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Mantle: 1.6.127
 - Inspirations: 1.2.3.38

**Comment by KnightMiner** [comment]
That is frost. Your cauldron is cold. Leave water in it, and it will become ice over time.

Heating it makes it not cold. Hence the frost going away. You can also in warmer biomes pack your cauldron in ice for the same effect.

I agree the texture is not the best, but I have not had time to improve it.
