### ISSUE TITLE
[1.16.5] CraftTweaker integrations?

### ISSUE THREAD

**Issue by SanjivanM** [KnightMiner/Inspirations#228]
Is CT support planned? I wanted to add some cauldron recipes like I did in the 1.12.2 version with CT, but I couldn't find CT documentation and it didn't seem like there was CT integrations in the mod already

**Comment by KnightMiner** [comment]
I have no plans to add CT integration. You have datapack support, which lets you fully add custom recipes. If someone else wants to write CT support, they are free.

**Comment by SanjivanM** [comment]
Ah, yes, I see the datapack pages for Cauldron recipes now, guess I should've looked harder :P 

however, I'm facing a problem with what looks to be my JSON syntax.  I'm trying to create a recipe such that when you right click a "boiling" cauldron with a block of cobblestone, it fills 1 level of lava

This is what I have so far from piecing together multiple different recipe syntaxes, but it doesn't load when I try and enable it.

Here's the relevant section of the log when reloading datapacks, not sure what I've done wrong, any help would be appreciated

piece of log with datapack error
[latest2.txt](https://github.com/KnightMiner/Inspirations/files/7836784/latest2.txt)

the JSON file
[cobblestone_to_lava.txt](https://github.com/KnightMiner/Inspirations/files/7836782/cobblestone_to_lava.txt)

[edit] logs and JSON uploaded as TXT files now

**Comment by KnightMiner** [comment]
You must have input contents, it is not optional. In the case of your recipe, lava would be a sensible content, as adding cobblestone to lava should be acceptable. If you set your levels right, you can have an empty cauldron up to an almost full one fillable.

In general most of the parts of the recipe are required, assume nothing is optional. If in doubt, copy and paste one of the provided recipes and make changes
