### ISSUE TITLE
[Feature Request] Finer config control over the cauldron + "potion crafting"

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#23]
I'd like to be able to disable the potion brewing function of the cauldron without removing the ability to store liquid potion in the cauldron.
I don't like how the cauldron steps on the toes of the brewing stand and makes blazes less valuable, but I also like the idea of using cauldrons as fancy semi-decorative potion storage. 

Additionally, be it either a complicated set of config options or crafttweaker support, I'd like to be able to make recipes that use the cauldron filled with liquid potion and "ingredients" to create items and the like.
This combined with a separate "storage only" config option would make the brewing stand and cauldron synergize with each other nicely.

**Comment by KnightMiner** [comment]
A config option to disable the brewing without the recipes might make sense, I will see about it.

CraftTweaker support will come as soon as I have time.

**Comment by KnightMiner** [comment]
Added in 0.1.2
