### ISSUE TITLE
With Quark Bugs

### ISSUE THREAD

**Issue by Noone746458** [KnightMiner/Inspirations#230]
**Describe the bug**
I found 2 bugs:
 - Right click harvest from Quark affects reeds and cacti. You can place reed or cacti, press right click and reed or cacti will return, but it will leave seeds and you can gather them. So this way you can produce seeds endlessly.

- Mushroom Stew required only 2 mushrooms instead of 4 for a full cauldron if you exactly drop them into cauldron. Right clicking works well and consumes 4. It works fine without Quark. Idk if some cauldron recipies are bugged too. I tried it with Beetroot and Potato but it seems works fine.

Tested with clear client with only forge and these mods.

**Versions:**
 - Minecraft: 1.12.2
 - Mantle: 1.3.3.55
 - Inspirations: 0.2.9

**Other mods required**
 - Quark: r1.6-179
 - AutoRegLib: 1.3-32

**Comment by KnightMiner** [comment]
Closing as I have moved on from 1.12, was reported a bit too late to get fixed.
