### ISSUE TITLE
Can't craft custom Bookshelves

### ISSUE THREAD

**Issue by Adidiii** [KnightMiner/Inspirations#233]
When I went to the crafting table, and attempted to craft bookshelves, I wasn't able to do it. I was able to make a weird "shelf" item, but I needed a bookshelf

**Screenshots: **
![Minecraft_ 1 16 5 - Singleplayer 2022-06-28 11_16_52](https://user-images.githubusercontent.com/108353476/176216711-034df928-4757-4691-adc5-8670b57f238a.png)
![Minecraft_ 1 16 5 - Singleplayer 2022-06-28 11_17_36](https://user-images.githubusercontent.com/108353476/176216743-e5827f10-006c-4ef3-b23d-70a2bb4deeca.png)

**Versions :**
 - Minecraft: 1.16.5
 - Mantle: 1.6.157
 - Inspirations: 1.2.3.38

There are no other mods that I used

**Comment by KnightMiner** [comment]
Shelves are bookshelves. You can put on books on them. I don't add anyrhing crafted with planks and paper
