### ISSUE TITLE
Shelves replace original inspirations bookshelves

### ISSUE THREAD

**Issue by vediis** [KnightMiner/Inspirations#238]
The original vanilla-faithful bookshelves in inspirations seem to have been replaced by shelves. Is this configurable at all? Several people have expressed a strong preference for the original bookshelf model.
New:
![image](https://user-images.githubusercontent.com/12003018/215017775-57c6d9d5-6fe3-47ac-a67c-c95bff3d08ab.png)
Original from github wiki:
![image](https://user-images.githubusercontent.com/12003018/215017726-b15e39f3-d47e-4af7-8910-96c859ab6ad7.png)

 - Minecraft: 1.16.5
 - Mantle: 1.16.5-1.6.157
 - Inspirations: 1.16.5-1.2.3.38

**Comment by vediis** [comment]
Ah, feature, not a bug. https://github.com/KnightMiner/Inspirations/issues/239
The question for original models remains!

**Comment by KnightMiner** [comment]
Shelves are bookshelves. Dislike the model? Change it. Just know that the new model holds 2 more books than the old one so there are really 0 disadvantages.
