### ISSUE TITLE
Add bookshelves back in

### ISSUE THREAD

**Issue by vediis** [KnightMiner/Inspirations#239]
Would it be possible to re-add bookshelves alongside the current shelves? They looked far more vanilla friendly and were replaced by shelves, although they only held books.
https://github.com/KnightMiner/Inspirations/commit/c7cb461f084a95fdaac601074627764b1ce33a1a

**Comment by KnightMiner** [comment]
... shelves are bookshelves. They still hold books, same as before. You can just hold far less books to hold an item.
