### ISSUE TITLE
Crash when placing water in cauldron

### ISSUE THREAD

**Issue by medsal15** [KnightMiner/Inspirations#3]
Crash report moved to https://pastebin.com/z6v9g6C9

**Comment by KnightMiner** [comment]
Please use pastebin for crash reports, I've done it for you this time.

This crash should not be happening. I have an access transformer on that field which would prevent the IllegalAccessError, so it means somehow one of your mods is breaking access transformers.

**Comment by medsal15** [comment]
Tried to launch Minecraft with only Mantle and Inspirations. Crashed again. https://pastebin.com/2Mkn8HFY

**Comment by KnightMiner** [comment]
Yep, that is the access transformer again. No idea why it's breaking since it was working for me.

**Comment by KnightMiner** [comment]
Okay, managed to find the issue and fixed with 9a6ccad. There will be a build on Curse shortly that fixes this.

**Comment by KnightMiner** [comment]
0.0.1b was just approved on CurseForge, fixing this issue.
