### ISSUE TITLE
[Request] Bookshelves for Plants2, and Rockhounding: Surface, woods

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#31]
What it says on the tin.

**Comment by KnightMiner** [comment]
Please explain what you are asking for. Does plants2 and rockhounding add woods which do not have booksheves generated? If so, the issue is likely on their side from not having wooden slabs or not using the ore dictionary.

**Comment by NotAVerb** [comment]
the non existence of said bookshelves led me to believe that the bookshelves were not automatically generated.
I just checked a plants slab. It's not ore dictionary-ed properly.
Rockhounding: Surface slabs aren't either, but they're not supposed to be because they're fossil woods.
Rockhounding has an option to add its woods to the ore dictionary, but I haven't tested to see if that option extends to its slabs.

I'll open an issue on the Plants tracker. I'd prefer for the Rockhounding slabs to be able to create shelves without needing to become "wooden".

**Comment by NotAVerb** [comment]
Plants has been patched.
I've also realized that seeing as the bookshelves have burn times, it doesn't make sense to use fossil woods.
