### ISSUE TITLE
[Suggestion] Rotatable hoppers

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#32]
Seeing as you're already willing to replace cauldrons, I was wondering if you would be willing to do something as drastic as this.

If this were to be done I think it would be good to allow shift-scrolling to select the orientation of the hopper.

**Comment by KnightMiner** [comment]
Please expand upon this request. You want to be able to change the orientation of hoppers on click? This sounds like you should use one of the many wrench mods instead.

**Comment by NotAVerb** [comment]
I just checked the hoppers with F3. I hadn't realized that the little tab that appears to connect them to the sides of chests was a fully different block rotation.

I meant that I wanted to be able to place hoppers on their sides and upside down. This would actually change how they pull in blocks.
This would have been a block replacement, but now that I know that the hopper already has rotations I'm not sure if it is possible.

**Comment by KnightMiner** [comment]
Ah. That is possible, but I personally don't feel it fits vanilla very well, hoppers always pulled from the bottom and pushed to the sides. I personally feel extraction from just the bottom feels balanced.

For what you are suggesting I would encourage checking out [Faucets and Filters](https://minecraft.curseforge.com/projects/faucets-and-filters) which adds an extracting block with that behavior.
