### ISSUE TITLE
[Suggestion] Allow The One Probe Readme into Bookshelf

### ISSUE THREAD

**Issue by Lethann** [KnightMiner/Inspirations#34]
I know it appears as a paper but it's really a manual and would be nice if it would go into the bookshelf.

**Comment by KnightMiner** [comment]
You can actually allow this your self. Check out the config options, one is for keywords which make something a book, the other let's you directly add a book yourself.

Ill leave this open for now so I can add it to the config by default.

**Comment by Lethann** [comment]
yea, the only reason why I mentioned it is that for those who are using modpacks on servers we're sorta limited by what is in the pack unless the server makes the changes (and my server admin hates doing that). If it's allowed by default would be a big help. Thanks!

**Comment by KnightMiner** [comment]
I've added it to the default config for the next version, though do note that it will have no effect unless the config file is regenerated.

**Comment by KnightMiner** [comment]
Added in 0.1.4
