### ISSUE TITLE
Chisel's carpets cannot be applied to stair blocks

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#36]
![2018-03-13_00 56 35](https://user-images.githubusercontent.com/30223331/37323345-086938c0-267b-11e8-9029-482acf5c2ffc.png)
Is it possible for chisel carpets to be made compatible with the stair placement feature? I'm guessing that they too would require block substitutions.
Would it be possible for their connected textures to still function?

**Comment by KnightMiner** [comment]
This is not something I can easily do, you are correct that I would have to replace every one of their carpet blocks. It would be easier and less likely to cause issues for them to just add the feature directly.
