### ISSUE TITLE
[Suggestion] Blacklist For Enlightened Bushes

### ISSUE THREAD

**Issue by InsomniaKitten** [KnightMiner/Inspirations#37]
The reason for this suggestion is that Enlightened Bushes are being generated from [Chromatic Foliage](https://minecraft.curseforge.com/projects/chromatic-foliage)'s leaves. Firstly, you don't appear to support modded subitems, so only the black (meta 0) chromatic leaves are craftable into enlightened bushes; secondly, this integration results in literally crafting coloured leaves into coloured leaves... And to me that makes no sense. I would appreciate a config to be able to blacklist leaves for cases such as this. For reference to the secondary issue regarding subitems, you can find my `Item#getSubItems` method here:

https://github.com/SleeplessDevelopment/ChromaticFoliage/blob/e18c564804742ef5adaf52e1e8e0a9ea5afc4c44/src/main/java/net/sleeplessdev/chromaticfoliage/item/ChromaBlockItem.java#L30-L37

If you would like me to open a separate issue regarding subitems, let me know.

**Inspirations version:** [0.1.3](https://minecraft.curseforge.com/projects/inspirations/files/2539041)

**Comment by KnightMiner** [comment]
Sub items were working last I checked, vanilla leaves use them and they work. I'll think about a blacklist, it's not easy due to the way the recipe works though  (same logic as the bookshelves so it would be a lot of special casing). In any case, you can just not craft them

**Comment by InsomniaKitten** [comment]
Oh, I see the issue... I don't override Block#getSubBlocks, which is what you are using. I assumed mods wouldn't be using it for a Block with an ItemBlock.

**Comment by InsomniaKitten** [comment]
Fixed subitems issue in [1.12-1.0.2](https://minecraft.curseforge.com/projects/chromatic-foliage/files/2541439). Should probably leave this issue open for the suggestion itself though, idk.

**Comment by KnightMiner** [comment]
In that case I think I will close this. I cannot think of a good way to add a blacklist without special casing my leaf recipes (which is shared by bookshelves as well), and in any case you do not have to use every leaf type in crafting.
