### ISSUE TITLE
Tesselating block model crash.

### ISSUE THREAD

**Issue by majijn** [KnightMiner/Inspirations#40]
I thought it would be cool to whitelist skulls so I can put them in the bookshelves, =/ but it turns out it was a REALLY bad idea on my part, rip that world.
[crash-2018-03-18_13.06.22-client.txt](https://github.com/KnightMiner/Inspirations/files/1823788/crash-2018-03-18_13.06.22-client.txt)

this one's DEFINITELY my fault but I thought that maybe this ...mess up may help someone else not repeat my mistakes at least

**Comment by KnightMiner** [comment]
I assume you tried vanilla skulls? Seems they have a null particle texture which I assumed was illegal. I'll throw a catch for that for the next version.

**Comment by majijn** [comment]
yes! it was vanilla skulls that i tried.

**Comment by KnightMiner** [comment]
Fixed to no longer crash in 0.1.4, it will just have a default color now.
