### ISSUE TITLE
[Bug?] JEI integration for anvil falling and block metadata

### ISSUE THREAD

**Issue by Dylan4ever** [KnightMiner/Inspirations#41]
Hi there!

In a personal pack, I've added 2 anvil falling interactions with blocks from the Erebus mod, namely, smashing Umberstone into Umbercobble and Umbercobble into Umbergravel. 

These are the lines I added:
# Erebus
			erebus:umberstone:0->erebus:umberstone:1
			erebus:umberstone:1->erebus:umbergravel

With the latter, JEI shows the correct recipe. With the former, however, both sides of the equation show Umbercobble (erebus:umberstone:1).

While in-game behaviour is as expected and properly respects metadata (only umberstone:0 can be smashed into umberstone:1, umberstone:2 through 6 are unaffected), the recipe shown in JEI is incorrect and thus, does not show up when looking at uses for umberstone:0, while that block is in fact the one that has an interaction with the falling anvil.

Hardly a big issue, especially since it does not break anything in-game, just a minor thing I noticed. Hopefully my explanation was sufficiently clear!

**Comment by KnightMiner** [comment]
Looks like it's due to how I grab the metadata for the result. I currently use damageDropped, but it must change to drop cobblestone. I do wonder why I'm not using  getPickBlock or so edging related, I'll mess around with it to see if I can find an easy function to call.

**Comment by KnightMiner** [comment]
Looking into this, there does not seem to be an easy fix. I can switch to using getMetaFromState, but most blocks do not convert 1 to 1 from meta to itemstack meta. damageDropped is pretty close but as can be seen here it may be used for other behavior. getPickBlock or getItem both require world access where the block may not exist.

**Comment by KnightMiner** [comment]
Should hopefully work in 0.1.4.
