### ISSUE TITLE
When There Is More Than One Input, One Is Still Used

### ISSUE THREAD

**Issue by EmosewaPixel** [KnightMiner/Inspirations#42]
This issue is related to the ModTweaker support you added. Here is what I mean by the title:
 I have this recipe here:
![image](https://user-images.githubusercontent.com/25333164/37718558-41035568-2d23-11e8-93d8-a7e6ed8b3361.png)
 When I have 1 Terracotta and try to click the Cauldron, nothing happens:
![image](https://user-images.githubusercontent.com/25333164/37718628-7116947c-2d23-11e8-8bde-1d300abf0786.png)
 When I have 2, I get 2 stained Terracotta, but only 1 Terracotta is used:
![image](https://user-images.githubusercontent.com/25333164/37718686-91f35fa4-2d23-11e8-8260-af2f36ac1adc.png)

**Comment by KnightMiner** [comment]
It is intentional that if you set a requirement of 2, you must have 2 items for the recipe to work. It seems that it is not properly consuming both items though, so I must have not fully implemented that behavior for the dye recipes.

**Comment by KnightMiner** [comment]
Fixed in 0.1.4
