### ISSUE TITLE
when water bottles are used on a cauldron in creative they produce empty glass bottles

### ISSUE THREAD

**Issue by xkforce** [KnightMiner/Inspirations#44]
I don't know if this is intentional or fixable through configuration but its inconsistent behavior that is considered to be a bug in vanilla.

**Comment by KnightMiner** [comment]
This is intentional for Inspirations, all cauldron recipes will copy the item to give the result when in creative. It's more effort than it is worth to special case which recipes should return the result in creative and which should not.
