### ISSUE TITLE
Redstone Torch Lever does not activate adjacent blocks

### ISSUE THREAD

**Issue by polski-g** [KnightMiner/Inspirations#45]
Torch Lever does work. but Redstone Torch Lever does not. See picture.

![Torches](https://i.imgur.com/RKgKxTg.png)

**Comment by polski-g** [comment]
Also in The One Probe, when you mouseover the redstone torch lever, it says "State: Off" even when its on.

**Comment by KnightMiner** [comment]
The Redstone torch lever behaves differently than a normal levee. Only the back emits power as the sides are inputs 

As for the One Probe, that is simply because i had to remake some states to support the toggling behavior, it is not exaxtly intentional but not really worrh trying to fix.

**Comment by polski-g** [comment]
Oh okay, I thought it was just a lever that told you if it was on or off (don't know if such a thing exists anywhere).
