### ISSUE TITLE
Notice: TaN Mechanics have changed

### ISSUE THREAD

**Issue by Sunconure11** [KnightMiner/Inspirations#46]
The ways of purifying water in TaN have changed. You might want to update your mod to accommodate the new changes.

**Comment by KnightMiner** [comment]
I just noticed, it is on my lust now. I probably can remove a lot of the logic since they changed vanilla water to be the dirty water.

**Comment by ilvrak** [comment]
is there a way to simply disable dirty water in cauldrons, without TaN removing?

**Comment by KnightMiner** [comment]
Disable the plugin in the modules

**Comment by KnightMiner** [comment]
Updated in 0.1.4
