### ISSUE TITLE
[feature request] JEI integration for potions

### ISSUE THREAD

**Issue by Zygus42** [KnightMiner/Inspirations#47]
I notice that the dying and souping in cauldrons have jei recipes, but the potion making in cauldrons is absent.  Would love to see that added also.

**Comment by KnightMiner** [comment]
Potion making with cauldrons is included. If you are not seeing it, you probably have it disabled or its some sort of mod conflict. If so, please post your game logs for me to look at.

**Comment by Zygus42** [comment]
Ah - I see.  You can see the recipes if you select use on a cauldron, but not if you click recipe on a potion.

**Comment by KnightMiner** [comment]
You need to use on the potion "fluids", the potion items are simply made using the fluids. I can try to add a more general JEI display for showing potion filling, but no plans right now.

**Comment by Zygus42** [comment]
All I'm currently doing is testing a new modpack i'm building, and am trying to figure out if any player is ever likely to click on either the cauldron or the potion liquids instead of the potion itself to see how it's made.  If they don't know it's there as an option, they will not use it.
