### ISSUE TITLE
[Suggestion] Secret bookshelf button

### ISSUE THREAD

**Issue by Kiyaku** [KnightMiner/Inspirations#51]
Similar to the brick/netherbrick buttons, a bookshelf that has 1 book act as a button when right clicked. 
Would make for good secret areas in libraries and such.

**Comment by KnightMiner** [comment]
If you use the Inspirations bookshelf, there is the trapped book which is a book emitting a redstone signal. I am not sure right now if a bookshelf like the bricks button makes the most sense as my bookshelves are sorta designed to replace the vanilla ones, but I'll consider it.

**Comment by Kiyaku** [comment]
Aha, i didn't see the trapped book, sorry about that.

I guess that would work as well, could have the book inside the bookshelf among other books and once pulled out, open doors, etc. Only downside is that people can take it with them, where as having it as a secret level/button thing, it's only useful for that one spot. But i'm mostly seeing this being used in a pre-defined area like a dungeon, and/or in adventure mode maps. Otherwise people would probably just tear down all the bookshelf anyway lol.

While i think having more options never hurts, the trapbook is probably good enough!

**Comment by KnightMiner** [comment]
Thinking on this more, I have no plans to add the bookshelf variant. The trapped book feels much more immersive for books.
