### ISSUE TITLE
[suggestion] add support for Carpeted Quark Trapdoors

### ISSUE THREAD

**Issue by ilvrak** [KnightMiner/Inspirations#52]

**Comment by KnightMiner** [comment]
I have no plans to add this feature in the near future. Carpeted trapdoors already take up 16 block IDs for each variant, adding support for the Quark trapdoors is another 80 blocks that need to be registered (which would be an absolute pain). In the future I may change the texture of the base trapdoor to be more generic across the wood types instead.
