### ISSUE TITLE
Request: Finer grain control of the config system, disable each feature one by one

### ISSUE THREAD

**Issue by PrinceOfAmber** [KnightMiner/Inspirations#53]
Use case:  I love most of the tweaks module, but I would like to be able to disable the "More Potions" feature.  

But i dont want to disable all of the Tweaks module, i want all of it on except "more potions" .

One config per "feature" as in one per sub-category on the wiki would be great.

**Comment by KnightMiner** [comment]
This already exists, there are two config files. Check out the main config file, not just the modules config.

**Comment by PrinceOfAmber** [comment]
LUL my bad i didnt realize there was multiple config files.  Thanks for replying!
