### ISSUE TITLE
Tinkers' Construct Slimy Ferns in flowerpots has no color

### ISSUE THREAD

**Issue by ilvrak** [KnightMiner/Inspirations#55]
Inspirations-1.12.2-0.1.4
TConstruct-1.12.2-2.10.1.84
forge-14.23.4.2705

![2018-06-04_10 05 21](https://user-images.githubusercontent.com/16130834/40894842-decde236-67de-11e8-9fe8-bc1de3551bc1.png)

**Comment by KnightMiner** [comment]
Huh, though I supported color tinting.

**Comment by KnightMiner** [comment]
Fixed in 0.1.5
