### ISSUE TITLE
Can't receive heartbeet when using right-click-to-harvest mods?

### ISSUE THREAD

**Issue by Kiyaku** [KnightMiner/Inspirations#56]
Heya,

it seems like if i use mods that let you harvest crops with a right click (such as SimpleHarvest), i don't ever receive any heartbeats. To test this, i went into a creative world, set the randomTick gamerule to 10000, planted a field of beetroots and ran around holding right click with bone meal in my hand. After several minutes i have yet to receive any. 

Then i switched to breaking the crops instead and planting seeds again and received heartbeets after a short while. Repeated this a few times to double check. 

Is this something that could be added? 
A config option to determine the drop chance of heartbeets would be great too. 

Cheers,
SC

**Comment by KnightMiner** [comment]
It sounds like the mods have implemented right click to not listen to the proper events. The way the drops work is by [listening to the HarvestDropsEvent](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/tweaks/TweaksEvents.java), which is the cleanest way to add extra drops. It is pretty easy for a mod to fire that, Tinkers Construct does so in [its right click harvest](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/tweaks/TweaksEvents.java) (for kamas and scythes). You should find heartbeets drop from either of those tools.

Looking at the code for SimpleHarvest, [they just get the block drops](https://github.com/TehNut/Harvest/blob/1.12/src/main/java/tehnut/harvest/ReplantHandlers.java#L17) and never fire the Forge event for me to add more drops, so its a SimpleHarvest bug.

I do think the rate being configurable makes sense. Honestly its a bit on the rare side anyways.

**Comment by Kiyaku** [comment]
Ah that makes sense, thanks. Will report it to the SimpleHarvest mod and see if they wanna change it up. In the meantime i'll try out another harvest mod, thanks! 

And yeah i find the heartbeet somewhat rare heh, so the config option would be amazing.

**Comment by KnightMiner** [comment]
I've made the drop a bit more common and added a config for the drop chance in 3a30b52

**Comment by KnightMiner** [comment]
@Kiyaku did you end up reporting to SimpleHarvest? I'd like to crosslink the issue so I can keep track of it

**Comment by Kiyaku** [comment]
@KnightMiner sorry i never did, i kinda stopped doing much with minecraft shortly after, until yesterday (good timing on asking lol). Will check it out today/this weekend and report to SimpleHarvest.

**Comment by Kiyaku** [comment]
Late, but reported it over here: https://github.com/TehNut/Harvest/issues/12

**Comment by KnightMiner** [comment]
Closing as the corresponding SimpleHarvest issue is closed.
