### ISSUE TITLE
Missing textures for Enlightened Bushes counterparts from Forestry

### ISSUE THREAD

**Issue by Snownee** [KnightMiner/Inspirations#57]
![image](https://user-images.githubusercontent.com/16059084/41499309-7783b598-71b0-11e8-9c52-26398db594cc.png)
Forge 2708

**Comment by KnightMiner** [comment]
I'm pretty sure those leaves use NBT to determine the texture, which is not something I can easily check for. Unfortunately, there is no easy way to detect which blocks have such a requirement.

**Comment by Charnuz** [comment]
I have come across this issue as well. However, it behaves somewhat strange. The texture starts working __after you place__ the matching Forestry leaf block in the world.

Have not tested behavior for reloading the world/restarting the game.

Before placing:
![before_place_item](https://user-images.githubusercontent.com/16440978/63211989-5b560d80-c0c4-11e9-834d-58e2bd8e4e7a.png)
![before_place_world](https://user-images.githubusercontent.com/16440978/63211992-6c9f1a00-c0c4-11e9-8065-a68f0dabad7e.png)


After placing:
![after_place_item](https://user-images.githubusercontent.com/16440978/63211993-758feb80-c0c4-11e9-8e5c-15266c937487.png)
![after_place_world](https://user-images.githubusercontent.com/16440978/63211994-7759af00-c0c4-11e9-8314-4d66bda67d40.png)

**Comment by KnightMiner** [comment]
Same as #28, I am closing this as I do not plan to handle NBT for textures.
