### ISSUE TITLE
Suggestion:Bedrock Edition Sheep Coloring

### ISSUE THREAD

**Issue by Wotzinator** [KnightMiner/Inspirations#59]
i just wanted to ask if you could implement a feature from the bedrock edition : if you color a sheep on the bedrock edition every part of the sheeps wool is colord ( [example](https://pm1.narvii.com/6182/57f9657c2bc42d2bcada5661cd1667b0cbb49267_hq.jpg) ) in the java edition this is not the case ( [example](https://vignette.wikia.nocookie.net/minecraft/images/b/be/Sheep-0.png/revision/latest?cb=20150718075531) ).

**Comment by SanjivanM** [comment]
https://svenhjol.github.io/Charm/116#:~:text=Sheared%20Sheep%20show%20their%20color

Charm does that as well, however, if this feature is added into Inspirations, will there be a compat checker that isables this feature if Charm is present?

**Comment by KnightMiner** [comment]
Since charm has this feature, I am just going to close this as it exists in another mod. I typically don't add compact checkers either, the config file lets you disable redundant features.
