### ISSUE TITLE
[Inspirations 0.15.0] Crash while trying to brew potions in a cauldron

### ISSUE THREAD

**Issue by CrossJaw** [KnightMiner/Inspirations#62]
I was excited to finally find a mod where you could brew potions with cauldrons. I quickly downloaded the mod and tried out brewing. 

I lit up a cauldren and as soon as I put nether wart in it, it crashed with this report:
https://hastebin.com/olilameyor.rb

**Comment by KnightMiner** [comment]
This crash makes no sense. For some reason its crashing from Thermal Foundation's potion fluid, but the way the cauldron functions does not use a potion fluid at all. Can you reproduce with just Inspirations and Thermal Expansion? Just Inspirations and Hardcore Questing? Just the three mods?

**Comment by KnightMiner** [comment]
Since there is no response and the paste seems to have expired, I'm closing this issue. If you can reproduce with minimal mods I'll take another look, but the crash did not appear to be related to my code.
