### ISSUE TITLE
Picking the block holding CTRL doesn't save what's inside in nbt

### ISSUE THREAD

**Issue by Mrbysco** [KnightMiner/Inspirations#63]
Currently if you Ctrl+Right-Click a cauldron with anything in it it will give you an item with 2 nbt tags.

But after placing it it doesn't actually contain whatever was in it.

**Comment by KnightMiner** [comment]
I've looked into this briefly and ran into a couple issues:

* The cauldron stores its fluid in NBT, but the level in metadata, meaning placing a cauldron is always empty as it places metadata 0
* For some reason, even if I force it to place metadata 3 it always gives me water, and I cannot find what is in charge of setting up the NBT in vanilla code.
* Pick block logic is client side only, and Forge never added proper events for it as most data is server side only. This means there is not much I can do to override it.

So for now it looks like this is can't fix.

**Comment by KnightMiner** [comment]
This is fixed in 1.16, and I am dropping support for 1.12. Only block that was giving me issues is the cauldron as Ctrl+pick block does not copy block states.
