### ISSUE TITLE
[Request] Config option to nerf brewing potions in cauldrons

### ISSUE THREAD

**Issue by AntidermisMC** [KnightMiner/Inspirations#68]
I'm currently trying to create a pack including Inspirations, and while I want to keep the cauldron's ability to brew potions, the presence of fire retaining blocks much earlier than netherrack means that the player is able to brew potions way earlier than he should, not to mention the fact that cauldron brewing doesn't require blaze powder. For this reason, I'd like to ask whether it would be possible to add a config option in order to nerf the cauldron's potion output so it makes a single potion per set of ingredients instead of 3, like the brewing stand.

**Comment by KnightMiner** [comment]
In the lat re st version, it makes two options per ingredient
