### ISSUE TITLE
Thermal Expansion & Immersive Engineering Compatibility

### ISSUE THREAD

**Issue by dragonshardz** [KnightMiner/Inspirations#71]
Hi, it would be super awesome if you could add a compatibility module for TE and IE to allow their respective fluid handling blocks (fluiducts, portable tanks, and pipes) to insert and remove fluids from the cauldron.

**Comment by KnightMiner** [comment]
This does not need specific mod compatibility, but I can explain the issue:

Cauldrons use a level property from 0 to 3, meaning all fluid transactions must happen in 333.333mb increments. Of course this is not possible, so I can either round down or up, either one causing a dup bug.

It might be possible with the bigger cauldrons, but all transactions must now happen in 250mb increments. I would ideally have compatibility with mods like Tinkers Construct and Ceramics's channels which output at a slower rate (6mb increments)

**Comment by dragonshardz** [comment]
So, in short, it's not possible to do something like set the fillstage to 3 when a TE fluiduct with a compatible fluid (Purified Water, Water, potions, etc.) is linked to the Cauldron, because :notch:

I hate this game sometimes.

**Comment by KnightMiner** [comment]
Well, its possible, it just means you have to fill in 1000mb increments. I'm working on a way to allow smaller increments, but thats what you get when you mix imperial and metric units

**Comment by dragonshardz** [comment]
I don't think anyone would be too upset with filling Cauldrons with fluids from TE ducts in 1k mb increments.

**Comment by KnightMiner** [comment]
Cauldrons now support 1b increments from any fluid pipe, or 250mb increments if using bigger cauldrons. If you want any more control, use a dispenser to extract using the new utilities feature
