### ISSUE TITLE
IE treated wood bookshelves

### ISSUE THREAD

**Issue by majijn** [KnightMiner/Inspirations#74]
I don't seem to be getting the option to make them, if this something that must be added on your end or can I make them by using the right nbt (I tried doing it with nbt but it didnt seem to want to work for me it always gave be one that looked like oak wood)

if the bookshelves dont need slabs , I would also like support for astral sorcery's infused wood types if possible

**Comment by KnightMiner** [comment]
Recipe requires slabs, so Astral Sorcerys wood is unlikely, I don't want to special case a recipe.

I can, however, see about a recipe using the treated wood slabs. Neither wood is oredicted as wood slabs I assume but I can add an override

**Comment by majijn** [comment]
can I make the bookshelves with AS woods with the proper nbt with a give command? or are slabs required to draw the bookshelves properly or something like that

and thank you so much!
the different patterns on the treated woods are so nice so I kept trying to /give them to no avail, I'm not sure what I was doing wrong.

**Comment by KnightMiner** [comment]
Oh, you certainly can do whatever with the give command, the recipe just sets the NBT to the proper block. You probably have an error in the NBT which is preventing it from working, hard to guess though. I suggest using something like `/ct hand` from CraftTweaker to view the NBT so its easier to see how to modify it.

**Comment by KnightMiner** [comment]
I've added support for this in 0d32088, though unfortunately due to the way it had to be implemented the extra variants will not show in JEI. Would be nice to have them show there and ideally to make the list loaded from the config, but its tricky to do with load stages.

**Comment by KnightMiner** [comment]
This was added in 0.2.2
