### ISSUE TITLE
Cauldron is too fast

### ISSUE THREAD

**Issue by Ravin890** [KnightMiner/Inspirations#78]
Could you possibly make it so brewing in a cauldron isn't instant? So for example have the brewing take some time to happen with a progress bar (something like how ex nihlio's barrel when making witch water is for example)

**Comment by KnightMiner** [comment]
Nope, that would involve making it a ticking TE and change it from the vanilla behavior. By default the cauldron only brews 2 potions per ingredient instead of 3 so the brewing stand still had a use.
