### ISSUE TITLE
When in creative mode, filling/modifying a normal cauldron consumes item but redstone barrel doesn't

### ISSUE THREAD

**Issue by Snownee** [KnightMiner/Inspirations#8]
Also, dyeing an item consume water but clearing color of a item doesn't

**Comment by KnightMiner** [comment]
This was mostly because the recipes do not distinguish between crafting and filling cauldron, while vanilla special cases every action. I doubt people will use the cauldron for crafting that much in creative anyways.

I'll take another look at how I want to handle creative for the cauldron.

**Comment by KnightMiner** [comment]
59e2660 will clean this up a bit. There may still be minor inconsistencies, but nothing worth fixing as I am not adding a creative check to the recipes themselves.

**Comment by Snownee** [comment]
Thanks! 😄

**Comment by KnightMiner** [comment]
Fixed in 0.1.2
