### ISSUE TITLE
Bookshelf rendering crash

### ISSUE THREAD

**Issue by the-realest-stu** [KnightMiner/Inspirations#80]
Some players on my server have been experiencing a crash caused by bookshelf models.

[Crash log](https://paste.ee/p/ZZAMm)

Inspirations 0.2.1
Forge 14.23.4.2715

**Comment by KnightMiner** [comment]
Somebody broken vanilla model loading. This is not something I can fix, find out which mod is breaking it so we can get this fixed.

Also, that is your game log, not the crash report. It contains the crash, sure, but also 11000 lines that are not the crash.

**Comment by KnightMiner** [comment]
This should be fixed in a recent Forge build, let me know if it happens again
