### ISSUE TITLE
Recipe Registration with oredictionary

### ISSUE THREAD

**Issue by TimGoll** [KnightMiner/Inspirations#81]
Some mods (quark) add different types of wooden trapdoors. You could support them if you'd change your recipe to use <ore:trapdoorWood> instead of the default minecraft one.

**Comment by KnightMiner** [comment]
I could, but my trapdoor has the texture of the vanilla one, and I'd rather not add another 16 variants per wood type. I'll consider this more

**Comment by TimGoll** [comment]
Ah yes. Adding 16*5 more trapdoors isn't a good idea. Maybe a config option?

**Comment by KnightMiner** [comment]
No, something as trivial as this won't be a config option, I just need to consider the best way to handle it. It may involve making a wood type neutral texture as I'll have to solve this before 1.13 anyways

**Comment by TimGoll** [comment]
this sounds actually pretty good. I can make a texture and a model for you, if you need one

**Comment by TimGoll** [comment]
Okay. I'll make a texure. Should it be in the vanilla style? One texture for all the sides? Because I could add an extra side texture if you want to.

**Comment by TimGoll** [comment]
![2018-08-26_11 14 02](https://user-images.githubusercontent.com/13639408/44626699-49161900-a921-11e8-876b-a3a13403f3aa.jpg)

What do you think about something so simple like this? It would look prettier if you add a seperate texture for the side.

**Comment by KnightMiner** [comment]
If you think it looks better with a side texture, go ahead. It looks pretty good, though in the PR make sure to add a shaderless screenshot.

**Comment by TimGoll** [comment]
okay. I'll do it later

**Comment by KnightMiner** [comment]
Added in 59868a7 which was released in 0.2.2
