### ISSUE TITLE
[feature request] Colured water is no real liquid

### ISSUE THREAD

**Issue by TimGoll** [KnightMiner/Inspirations#86]
Not a bug, but a feature request. Is there a reason behind your decision that coloured water is no forge liquid? It would be really cool to be able to use pipes to transport the coloured water and use crafttweaker to use this water in other machines as a dye

**Comment by KnightMiner** [comment]
I mostly did not make it a proper liquid because its a pain to make a liquid fully behave like water without breaking other mod assumptions about liquids. I may add it as just a fluid in the future with no placable form, but that is best covered by #18.

**Comment by TimGoll** [comment]
that's what I meant. I do not need it to be placeable. But it's not important either

**Comment by KnightMiner** [comment]
Yeah, I'm thinking at this point my best bet is making a set of colored liquids and special case the in the liquid logic, then letting them work with a mod like placeable colored water if you want that functionality. It just takes some rethinking
