### ISSUE TITLE
A way to itemstage the added potion liquids?

### ISSUE THREAD

**Issue by Guinaro** [KnightMiner/Inspirations#88]
When using the option in the config
# Allows cauldrons to be filled with potions and support brewing [default: true]
        B:potions=true

Liquid Icons for potion fluids are added to JEI.
Currently you cannot hide them manually in JEI.
I would like to be able to hide them with ItemStages. If that is not possible could you provide a config option to still allow brewing (and especially allow filling of glass bottles!) but hiding these extra fluid icons in JEI?
It seems I can disable this option, and having in the potions part, brewing still enabled. The result is I can still brew a potion, but I cannot fill a glass bottle with the potion inside the cauldron, but the extra liquid icons for the various potions are not present in JEI.

It could also be an option to make the potion fluids actually behave like a fluid stack. As we can hide liquidstacks with Itemstages. I can only guess what impact this would have on minecraft and your mod.

Thank you for your consideration.
Guinaro

**Comment by KnightMiner** [comment]
Can you further explain your issue? Not being able to hide them sounds like a JEI bug, which it might be worth talking to mezz about. I could add a config option to hide them myself, but that should be handled by JEI already.

**Comment by KnightMiner** [comment]
I am going to close for lack of information, this should no longer be an issue in my current 1.14 plans
