### ISSUE TITLE
Crash with last forge

### ISSUE THREAD

**Issue by wenlfs** [KnightMiner/Inspirations#89]
The game crash on start up with the new forge version.

Inpirations: 1.12.2-0.2.2
Mantle: 1.12-1.3.2.24
Forge: 14.23.5.2768

Crash report: https://pastebin.com/EsP4xBZw

**Comment by TacticalUniverse** [comment]
I just got this on the new build when I went to start a server up on the new Forge 2768

**Comment by KnightMiner** [comment]
Yeah, Forge removed a AT I was using, I guess I need to add it on my side now.

**Comment by BrisingrAerowing** [comment]
This explains why I suddenly got a crash after updating Forge. I'll just go back to the previous version I was using.

**Comment by DaedalusGame** [comment]
Supposedly, MixPredicates are registry thingies now so they have an event you can use for registering your recipes now

**Comment by KnightMiner** [comment]
MixPredicates are not a proper registry, Potion types are. MixPredicate just got patched in the crossfire and now ATs no longer work on it. So yeah, the PR (#90 for cross linking)
