### ISSUE TITLE
[Suggestion] Chocolate Milk, removes negative effects only

### ISSUE THREAD

**Issue by Insane-96** [KnightMiner/Inspirations#92]
Chocolate Milk. Like the milk, but when drunk will remove only bad effects.
Can be created in a Cauldron

**Comment by KnightMiner** [comment]
I cannot see myself adding this specifically. Part of the weakness of milk is it removes positive effects, cocoa beans are much too cheap to remove that weakness. I could see myself adding chocolate milk in the future, just not with this specific function

**Comment by majijn** [comment]
@Insane-96 the mod [bird's foods](https://minecraft.curseforge.com/projects/birds-foods) has what you're looking for , several instances of the effect you're after actually.
