### ISSUE TITLE
Potion of Resist conflict

### ISSUE THREAD

**Issue by piedpipr314** [KnightMiner/Inspirations#94]
Potion of Resistance (Shulker Shell in Awkward Potion inside Cauldron) conflicts with EnderIO's Levitation potion.  Actually gives EnderIO potion as a priority.  I've tried looking through configs to see if it can be changed in either mod and no luck.

**Comment by KnightMiner** [comment]
Can you simply disable the Ender IO one? I also add my own Levitation potion.

I can look into a config option to set the item, but it's quite annoying to deal with, so maybe just individual toggles on each type. Will have to think about that one

**Comment by piedpipr314** [comment]
If it's inside the config files in EnderIO, I'm not finding it.  I can't find where any of the potion recipes are actually.

**Comment by piedpipr314** [comment]
I might be able to offer a suggestion:  perhaps a purpur block or chorus flower?  It is equally in the end (end game vanilla), it might suit your needs.

**Comment by KnightMiner** [comment]
I chose the shell because resistance is a pretty powerful effect (flat 20% damage reduction) and the shells are pretty rare, purpur is way too common for such an effect.

**Comment by piedpipr314** [comment]
Gotcha, just trying to help.  I might see if I can push this to SleepyTrousers to see if they know how this can be fixed on EnderIO's side.

**Comment by KnightMiner** [comment]
Closing as the Ender IO issue was closed
