### ISSUE TITLE
Separate charged arrow configuration from redstone charge config

### ISSUE THREAD

**Issue by beta-phenylethylamine** [KnightMiner/Inspirations#95]
It seems like charged arrows are the only thing in this mod that isn't possible to disable without disabling the whole tools module, if there isn't a strong reason for this I'd really like to suggest it be made configurable, since the redstone charge is very helpful to me but I'd really like to avoid things that (to me) feel blatantly non-vanilla like the charged arrows

**Comment by KnightMiner** [comment]
Disable the redstone charges/charger, it's tied to that config IIRC. Might make sense to separate it though

**Comment by beta-phenylethylamine** [comment]
It isn't, according to [Line 101 of InspirationsTools.java](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/tools/InspirationsTools.java#L101), it seems to just be undisableable

**Comment by beta-phenylethylamine** [comment]
oh wait, i see

**Comment by beta-phenylethylamine** [comment]
ah, okay, I see!

Regardless, it would probably be useful to separate the config for the two so I'll leave this open and rename it.
