### ISSUE TITLE
Recipe for bookshelfs are not displaying in JEI

### ISSUE THREAD

**Issue by techwulf** [KnightMiner/Inspirations#97]
I'm working with version 0.2.3 of Inspirations

**Comment by KnightMiner** [comment]
Please post a copy of your game log (using a site like Pastebin). It works fine on my side. Also, please give a mod list, including JEI, Forge, and Mantle versions

**Comment by techwulf** [comment]
I'm using Forge 14.23.5.2768

The latest log.
https://pastebin.com/6g1Kzndb

The current modlist.
https://pastebin.com/AVaww03w

I'll start doing some tests as well. Running it without certain other mods, upgrading the version of Forge I'm using. I also double checked all my zenscripts with crafttweaker to make sure I didn't accidentally disable the recipes.

**Comment by KnightMiner** [comment]
Looks like the JEI plugin errored before it had a chance to load the recipes. Somehow it ended up with a block smashing recipe containing a null. Not sure how it got there, but I can add a catch for it.

**Comment by techwulf** [comment]
You can probably remove this issue. I figured out why it wasn't loading the recipes. In the config file I must've messed up a mass file edit with vim. One third of every character containing line in the config file was missing the first two characters. Sorry about the unnecessary issue.

**Comment by KnightMiner** [comment]
No, I actually noticed a problem where invalid config will cause this bug, so I need to fix it eventually anyways

**Comment by KnightMiner** [comment]
Fixed in 0.2.4
