### ISSUE TITLE
Server kicked player with

### ISSUE THREAD

**Issue by ghost** [KnightMiner/Inspirations#98]
https://paste.dimdev.org/pabeyuqazu.mccrash

Withered Bone from Inspirations mod does not want to go into storage drawer. instead it crashes my client.

**Comment by KnightMiner** [comment]
Seems unrelated to storage drawers, just a wrong module check for one of the item registrations.

**Comment by TacticalUniverse** [comment]
ok

**Comment by KnightMiner** [comment]
Fixed in 0.2.4
